#!/usr/bin/env python3
"""docs/verification/2026-09-12b_findings.json + dispositions_2026_09_12b.py -> docs/VERIFICATION_2026-09-12b.md."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from dispositions_2026_09_12b import GAPS, ISSUES, MAP  # noqa: E402

R = json.load(open(os.path.join(HERE, "2026-09-12b_findings.json")))
F = {f["id"]: f for f in R["findings"]}
mapped = [i for ids in MAP.values() for i in ids]
assert sorted(mapped) == sorted(F), (set(F) - set(mapped), set(mapped) - set(F))
assert len(mapped) == len(set(mapped)), "a finding is mapped twice"
assert set(MAP) == set(ISSUES) and len(GAPS) == len(R["gaps"])
sev = {"critical": 0, "major": 1, "minor": 2}
for h, ids in MAP.items():
    worst = min((F[i]["severity"] for i in ids), key=sev.get)
    assert ISSUES[h][0] == worst, (h, ISSUES[h][0], worst)
counts = {s: sum(1 for f in R["findings"] if f["severity"] == s) for s in sev}
verd = {v: sum(1 for f in R["findings"] if f["verdict"] == v) for v in ("real", "partly", "refuted", "unjudged")}
L = ["# Third verification of the revision work (2026-09-12/13)", "",
     "Seven independent verifiers (referee-round recomputation, seed replicates and the seed rule, truth relabelling,",
     "a referee's read of the whole paper, the macro generator, docs and ledger, reproducibility and CI) checked",
     "everything added after the second pass (commits f2b4a21..c4bf5f3); each slice's findings were re-run by an",
     "adversarial checker, and a completeness critic looked for what nobody had covered. Raw record:",
     "`docs/verification/2026-09-12b_findings.json`; dispositions: `docs/verification/dispositions_2026_09_12b.py`",
     "(this file is generated by `docs/verification/build_doc_2026_09_12b.py`, which asserts that every finding is",
     "mapped to exactly one issue and that each issue's severity is its worst finding's).", "",
     f"**{len(F)} findings: {counts['critical']} critical, {counts['major']} major, {counts['minor']} minor; "
     f"adversarial verdicts {verd['real']} real, {verd['partly']} partly, {verd['refuted']} refuted.** They group into {len(ISSUES)} issues.", "",
     "## What changed as a result", "",
     "* **The seed rule was misapplied.** The released run's rate-weighted lead over round 3 does exceed the weighted",
     "  seed range, and the extra-training and physics verdicts flip with the budget. The three seeds are now a rough",
     "  scale applied per budget and weighting (Table tab:seeds): the measured pauses lead everywhere; the extra",
     "  training carries false alarms and the low budgets, the physics the high budget, mean recall and the largest",
     "  rho/|u0| bins (per event only); the recommended recipe's lead over round 3 is not established.",
     "* **The truth-label measurements were re-referenced** to the generator's own rule (a single-lens refit on the",
     "  surviving epochs of each binary's rebuilt noise-free curve). The first reference was matched by construction.",
     "* **Referee round:** the floor arms are partly the same events; the colour effect is lower variable-class",
     "  precision; the colour fine-tune contrast depended on the kept epoch; the every-class scan is also reported with",
     "  F146 alone, where purity is much lower; the per-event inputs are archived.",
     "* **Paper:** a stale Table 5 note, the Introduction, the Conclusion's account of open tests, and a dozen smaller",
     "  wording and labelling fixes; every new directional sentence has a fail-closed guard, and the guards are tested.", "",
     "## Issues", "", "| id | severity | issue | disposition | findings |", "|---|---|---|---|---|"]
for h in sorted(ISSUES):
    s_, t, d = ISSUES[h]
    L.append(f"| {h} | {s_} | {t} | {d} | {', '.join(MAP[h])} |")
L += ["", "## Completeness critic", "", "| # | target | disposition |", "|---|---|---|"]
for i, g in enumerate(R["gaps"]):
    L.append(f"| {i + 1} | {g['target'][:160].replace('|', '/')} | {GAPS[i]} |")
L += ["", "## Left open", "",
      "* Rewriting published git history to remove an old AWS account id and e-mail address (I54) is the author's call.",
      "* The abstract is longer than submitted (I39); A&C's limit was not checked.",
      "* Absolute local paths in artifacts (I55) are kept as provenance."]
out = os.path.join(os.path.dirname(os.path.dirname(HERE)), "docs", "VERIFICATION_2026-09-12b.md")
open(out, "w").write("\n".join(L) + "\n")
print(f"wrote {os.path.relpath(out)}")
