#!/usr/bin/env python3
"""docs/verification/2026-09-12b_findings.json + dispositions_2026_09_12b.py -> docs/VERIFICATION_2026-09-12b.md."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from dispositions_2026_09_12b import GAPS, ISSUES, MAP  # noqa: E402

R = json.load(open(os.path.join(HERE, "2026-09-12b_findings.json")))
F = {f["id"]: f for f in R["findings"]}
mapped = [i for ids in MAP.values() for i in ids]
assert sorted(mapped) == sorted(F), (set(F) - set(mapped), set(mapped) - set(F))
assert len(mapped) == len(set(mapped)), "a finding is mapped twice"
assert set(MAP) == set(ISSUES) and len(GAPS) == len(R["gaps"])
sev = {"critical": 0, "major": 1, "minor": 2}
for h, ids in MAP.items():
    worst = min((F[i]["severity"] for i in ids), key=sev.get)
    assert ISSUES[h][0] == worst, (h, ISSUES[h][0], worst)
counts = {s: sum(1 for f in R["findings"] if f["severity"] == s) for s in sev}
verd = {v: sum(1 for f in R["findings"] if f["verdict"] == v) for v in ("real", "partly", "refuted", "unjudged")}
L = ["# Third verification of the revision work (2026-09-12/13)", "",
     "Seven independent verifiers (referee-round recomputation, seed replicates and the seed rule, truth relabelling,",
     "a referee's read of the whole paper, the macro generator, docs and ledger, reproducibility and CI) checked",
     "everything added after the second pass (commits f2b4a21..c4bf5f3); each slice's findings were re-run by an",
     "adversarial checker, and a completeness critic looked for what nobody had covered. Raw record:",
     "`docs/verification/2026-09-12b_findings.json`; dispositions: `docs/verification/dispositions_2026_09_12b.py`",
     "(this file is generated by `docs/verification/build_doc_2026_09_12b.py`, which asserts that every finding is",
     "mapped to exactly one issue and that each issue's severity is its worst finding's).", "",
     f"**{len(F)} findings: {counts['critical']} critical, {counts['major']} major, {counts['minor']} minor; "
     f"adversarial verdicts {verd['real']} real, {verd['partly']} partly, {verd['refuted']} refuted.** They group into {len(ISSUES)} issues.", "",
     "## What changed as a result", "",
     "* **The seed rule was misapplied.** The released run's rate-weighted lead over round 3 does exceed the weighted",
     "  seed range, and the extra-training and physics verdicts flip with the budget. The three seeds are now a rough",
     "  scale applied per budget and weighting (Table tab:seeds): the measured pauses lead everywhere; the extra",
     "  training carries false alarms and the low budgets, the physics the high budget, mean recall and the largest",
     "  rho/|u0| bins (per event only); the recommended recipe's lead over round 3 is not established.",
     "* **The truth-label measurements were re-referenced** to the generator's own rule (a single-lens refit on the",
     "  surviving epochs of each binary's rebuilt noise-free curve). The first reference was matched by construction.",
     "* **Referee round:** the floor arms are partly the same events; the colour effect is lower variable-class",
     "  precision; the colour fine-tune contrast depended on the kept epoch; the every-class scan is also reported with",
     "  F146 alone, where purity is much lower; the per-event inputs are archived.",
     "* **Two errors older than the revision (critic):** the 14.9M-event stress suite was scored with the stage-5",
     "  checkpoint, not the released model; a regenerated subset scored with both now gives the released model's numbers",
     "  (Table tab:stress), and shows that the suite's sub-day 'PSPL recall' mixed in demoted binaries: most sub-day",
     "  single lenses are called anomalies. The appendix training recipe described the base run's defaults; it now",
     "  gives the six-stage chain.",
     "* **Paper:** a stale Table 5 note, the Introduction, the Conclusion's account of open tests, and a dozen smaller",
     "  wording and labelling fixes; every new directional sentence has a fail-closed guard, and the guards are tested.", "",
     "## Issues", "", "| id | severity | issue | disposition | findings |", "|---|---|---|---|---|"]
for h in sorted(ISSUES):
    s_, t, d = ISSUES[h]
    L.append(f"| {h} | {s_} | {t} | {d} | {', '.join(MAP[h])} |")
L += ["", "## Completeness critic", "", "| # | target | disposition |", "|---|---|---|"]
for i, g in enumerate(R["gaps"]):
    L.append(f"| {i + 1} | {g['target'][:160].replace('|', '/')} | {GAPS[i]} |")
L += ["", "## Left open", "",
      "* Rewriting published git history to remove an old AWS account id and e-mail address (I54) is the author's call.",
      "* The abstract is longer than submitted (I39); A&C's limit was not checked.",
      "* Absolute local paths in artifacts (I55) are kept as provenance."]
# ---- addendum: the fourth verification of the final state (2026-09-13) --------------------------------------------
import dispositions_2026_09_13 as D4                                    # noqa: E402
R4 = json.load(open(os.path.join(HERE, "2026-09-13_fourth_findings.json")))
ids4 = [f["id"] for f in R4["findings"]]
assert set(ids4) == set(D4.DISPO) and len(ids4) == len(set(ids4)), "every fourth-verification finding needs one disposition"
assert len(R4["gaps"]) == len(D4.GAPS4)
c4 = {s_: sum(1 for f in R4["findings"] if f["severity"] == s_) for s_ in ("critical", "major", "minor")}
v4 = {v: sum(1 for f in R4["findings"] if f["verdict"] == v) for v in ("real", "partly", "refuted")}
L += ["", "## Addendum: fourth verification of the final state (2026-09-13)", "",
      "Six verifiers (the released model's stress numbers, the RMDC26 cascade reduced independently, the revision ledger,",
      "the changed manuscript text, code/artifacts/CI, the appendix and documentation), one adversarial checker per slice",
      "and a completeness critic checked the state after the fixes above (commit 9c04593). Raw record:",
      "`docs/verification/2026-09-13_fourth_findings.json`; dispositions: `docs/verification/dispositions_2026_09_13.py`.", "",
      f"**{len(ids4)} findings: {c4['critical']} critical, {c4['major']} major, {c4['minor']} minor; adversarial verdicts "
      f"{v4['real']} real, {v4['partly']} partly, {v4['refuted']} refuted.**", "",
      "The main corrections: the regenerated stress subset had used a fixed generator for the sub-day sweep (now regenerated",
      "with the July generator's peak-time draw, and described as a new realisation of the suite's populations, compared",
      "within itself); the faint sweep's anomaly precision reflected its class mix (the paper now quotes mix-independent",
      "false-anomaly rates); the RMDC26 cascade is compared with the in-house scan stratum by stratum; the referee round's",
      "per-event archive had never been committed; the appendix had described an earlier simulation run and an unsourced",
      "benchmark; Sec. results had located the in-distribution misses at weak anomalies, where the artifact puts them at",
      "wide separations.", "",
      "| id | severity | verdict | finding | disposition |", "|---|---|---|---|---|"]
for f in sorted(R4["findings"], key=lambda f: (("critical", "major", "minor").index(f["severity"]), f["id"])):
    L.append(f"| {f['id']} | {f['severity']} | {f['verdict']} | {f['claim'][:200].replace('|', '/')} | {D4.DISPO[f['id']]} |")
L += ["", "### Completeness critic (fourth verification)", "", "| # | severity | target | disposition |", "|---|---|---|---|"]
for i, g in enumerate(R4["gaps"]):
    L.append(f"| {i + 1} | {g['severity']} | {g['target'][:160].replace('|', '/')} | {D4.GAPS4[i]} |")
L += ["", "Left open after the fourth verification: the abstract's length (about 380 words) and the plain-text abstract in",
      "the untracked `paper/SUBMISSION_FIELDS.txt` (the author's, before resubmitting); AUDIT finding 14 (the stage-6 cache's",
      "shard indices, on S3); the audited F087/F213 constants against the current Roman tables (network); rewriting published",
      "git history (I54)."]
# ---- second addendum: the fifth verification (2026-09-14) ---------------------------------------------------------
import dispositions_2026_09_14 as D5                                    # noqa: E402
R5 = json.load(open(os.path.join(HERE, "2026-09-14_fifth_findings.json")))
ids5 = [f["id"] for f in R5["findings"]]
assert set(ids5) == set(D5.DISPO) and len(ids5) == len(set(ids5)), "every fifth-verification finding needs one disposition"
assert len(R5["gaps"]) == len(D5.GAPS5)
c5 = {s_: sum(1 for f in R5["findings"] if f["severity"] == s_) for s_ in ("critical", "major", "minor")}
v5 = {v: sum(1 for f in R5["findings"] if f["verdict"] == v) for v in ("real", "partly", "refuted")}
L += ["", "## Addendum 2: fifth verification (2026-09-14)", "",
      "Six verifiers (Sec. results, the RMDC26 cascade, the appendix and Data availability, the stress numbers, code and",
      "tests, a whole-paper read) and one adversarial checker per slice checked the state after the fourth verification's",
      "fixes (commit 9e95776). The completeness critic stalled on all six attempts and returned nothing; the sixth check",
      "below re-ran it. Raw record: `docs/verification/2026-09-14_fifth_findings.json`; dispositions:",
      "`docs/verification/dispositions_2026_09_14.py`.", "",
      f"**{len(ids5)} findings: {c5['critical']} critical, {c5['major']} major, {c5['minor']} minor; adversarial verdicts "
      f"{v5['real']} real, {v5['partly']} partly, {v5['refuted']} refuted.**", "",
      "The main corrections: the fourth round's Sec. results rewrite had denied that misses concentrate at weak anomalies,",
      "but at smaller separations they do (the paper now names two sources: wide binaries, missed at every evidence",
      "strength, and near-floor anomalies); the faint sweep's precision is set by faint photometry, not by its class mix",
      "(a natural-mix counterfactual gives 0.152 against 0.726); the regenerated wide-separation tier labels 27% fewer",
      "detectable anomalies than the set; the RMDC26 cascade's optimism check compared an F146-only rate with a three-band",
      "one; the stratum-wise cascade directions are stated with their counting noise; the appendix's regeneration cause,",
      "throughput and loss description were corrected; the stress evaluations are now archived per event.", "",
      "| id | severity | verdict | finding | disposition |", "|---|---|---|---|---|"]
for f in sorted(R5["findings"], key=lambda f: (("critical", "major", "minor").index(f["severity"]), f["id"])):
    L.append(f"| {f['id']} | {f['severity']} | {f['verdict']} | {f['claim'][:200].replace('|', '/')} | {D5.DISPO[f['id']]} |")
# ---- third addendum: the sixth check (2026-09-14) ------------------------------------------------------------------
import dispositions_2026_09_14b as D6                                   # noqa: E402
R6 = json.load(open(os.path.join(HERE, "2026-09-14_sixth_findings.json")))
ids6 = [f["id"] for f in R6["findings"]]
assert set(ids6) == set(D6.DISPO) and len(ids6) == len(set(ids6)), "every sixth-check finding needs one disposition"
assert len(R6["gaps"]) == len(D6.GAPS6)
c6 = {s_: sum(1 for f in R6["findings"] if f["severity"] == s_) for s_ in ("critical", "major", "minor")}
v6 = {v: sum(1 for f in R6["findings"] if f["verdict"] == v) for v in ("real", "partly", "refuted")}
L += ["", "## Addendum 3: sixth check (2026-09-14)", "",
      "Three reviewers (paper text and numbers; code, artifacts and tests; docs and records) checked the fifth round's",
      "fixes (9e95776..2133a41), one adversarial checker per slice judged their findings, and the completeness critic that",
      "had stalled in the fifth verification was re-run with a compact summary of that round's coverage. Raw record:",
      "`docs/verification/2026-09-14_sixth_findings.json`; dispositions: `docs/verification/dispositions_2026_09_14b.py`.", "",
      f"**{len(ids6)} findings: {c6['critical']} critical, {c6['major']} major, {c6['minor']} minor; adversarial verdicts "
      f"{v6['real']} real, {v6['partly']} partly, {v6['refuted']} refuted; the critic found {len(R6['gaps'])} gaps "
      f"({sum(1 for g in R6['gaps'] if g['severity'] == 'major')} major).**", "",
      "The main corrections: the in-house cascade's daily and two-day grid rows had skipped the season's last cut (a",
      "coarser grid lowers the premature rate at almost unchanged detection, not the reverse); the truncation ablation's",
      "argmax reversal rests on the coarse 7.2 d onset and is not established; the inference throughput of the previous",
      "revision was measured under load (1,015 per second on an idle machine); the matched-density test's low-density",
      "failure is empty two-hour bins, not sparsity (a regular grid keeps working); wide binaries are missed at a similar",
      "rate only up to dchi2 = 1e6; the generator is not unchanged for the out-of-range sweeps; the RMDC26 stratum",
      "statements now rest on Fisher tests and bootstrap intervals; the weighted calibration's mid-range is over-confident.", "",
      "| id | severity | verdict | finding | disposition |", "|---|---|---|---|---|"]
for f in sorted(R6["findings"], key=lambda f: (("critical", "major", "minor").index(f["severity"]), f["id"])):
    L.append(f"| {f['id']} | {f['severity']} | {f['verdict']} | {f['claim'][:200].replace('|', '/')} | {D6.DISPO[f['id']]} |")
L += ["", "### Completeness critic (re-run in the sixth check)", "", "| # | severity | target | disposition |", "|---|---|---|---|"]
for i, g in enumerate(R6["gaps"]):
    L.append(f"| {i + 1} | {g['severity']} | {g['target'][:160].replace('|', '/')} | {D6.GAPS6[i]} |")
L += ["", "Left open after the sixth check: per-directory stamps in the stress re-scoring (code6-07); a reduction of the",
      "referee round from its archive alone; per-event recomputation of the labelling ablation (its shards and checkpoints",
      "are on the Modal volume); the stage-5 weights and the stress suite's per-event predictions (not distributed);",
      "AUDIT finding 14 (S3); rewriting published git history (I54), the author's call."]
# ---- fourth addendum: the seventh check (2026-09-14) ----------------------------------------------------------------
import dispositions_2026_09_14c as D7                                   # noqa: E402
R7 = json.load(open(os.path.join(HERE, "2026-09-14_seventh_findings.json")))
ids7 = [f["id"] for f in R7["findings"]]
assert set(ids7) == set(D7.DISPO) and len(ids7) == len(set(ids7)), "every seventh-check finding needs one disposition"
assert len(R7["gaps"]) == len(D7.GAPS7)
c7 = {s_: sum(1 for f in R7["findings"] if f["severity"] == s_) for s_ in ("critical", "major", "minor")}
v7 = {v: sum(1 for f in R7["findings"] if f["verdict"] == v) for v in ("real", "partly", "refuted")}
L += ["", "## Addendum 4: seventh check (2026-09-14)", "",
      "A narrow check of the sixth check's fixes (2133a41..52e2d8c): paper, code and docs reviewers, one adversarial",
      "checker per slice and a completeness critic limited to those changes. The first launch stalled; the relaunch lost",
      "four agents to a usage limit and was resumed. Raw record: `docs/verification/2026-09-14_seventh_findings.json`;",
      "dispositions: `docs/verification/dispositions_2026_09_14c.py`.", "",
      f"**{len(ids7)} findings: {c7['critical']} critical, {c7['major']} major, {c7['minor']} minor; adversarial verdicts "
      f"{v7['real']} real, {v7['partly']} partly, {v7['refuted']} refuted; the critic found {len(R7['gaps'])} targets, one "
      "with a guard gap.**", "",
      "The main corrections: the ablation paragraph had claimed more than the 7.2 d onset grid records (the first-detectable",
      "onset can lie before the previous grid cut); the matched-density test's regular grid still loses a third of recall",
      "to thinning (full cadence 0.94), so empty bins explain the collapse to zero but not everything; the calibration's",
      "error comes mostly from the over-confident mid-range; one stratum difference is only nominally resolved; empty bins",
      "are now counted with the model's own binning; several docs and records repeated superseded claims.", "",
      "| id | severity | verdict | finding | disposition |", "|---|---|---|---|---|"]
for f in sorted(R7["findings"], key=lambda f: (("critical", "major", "minor").index(f["severity"]), f["id"])):
    L.append(f"| {f['id']} | {f['severity']} | {f['verdict']} | {f['claim'][:200].replace('|', '/')} | {D7.DISPO[f['id']]} |")
L += ["", "### Completeness critic (seventh check)", "", "| # | severity | target | disposition |", "|---|---|---|---|"]
for i, g in enumerate(R7["gaps"]):
    L.append(f"| {i + 1} | {g['severity']} | {g['target'][:160].replace('|', '/')} | {D7.GAPS7[i]} |")
# ---- fifth addendum: the eighth check (2026-09-15) -----------------------------------------------------------------
import dispositions_2026_09_15 as D8                                    # noqa: E402
R8 = json.load(open(os.path.join(HERE, "2026-09-15_eighth_findings.json")))
ids8 = [f["id"] for f in R8["findings"]]
assert set(ids8) == set(D8.DISPO) and len(ids8) == len(set(ids8)), "every eighth-check finding needs one disposition"
assert len(R8["gaps"]) == len(D8.GAPS8)
c8 = {s_: sum(1 for f in R8["findings"] if f["severity"] == s_) for s_ in ("critical", "major", "minor")}
v8 = {v: sum(1 for f in R8["findings"] if f["verdict"] == v) for v in ("real", "partly", "refuted")}
L += ["", "## Addendum 5: eighth check (2026-09-15)", "",
      "A narrow check of the commits no round had read (52e2d8c..e65a510: the seventh-round fixes, the 2026-09-14 length cut,",
      "the new abstract and Appendix B): prose, front-matter/captions/tables and records slices, a refuter per slice and a",
      "narrow critic. Raw record: `docs/verification/2026-09-15_eighth_findings.json`; dispositions:",
      "`docs/verification/dispositions_2026_09_15.py`.", "",
      f"**{len(ids8)} findings: {c8['critical']} critical, {c8['major']} major, {c8['minor']} minor; adversarial verdicts "
      f"{v8['real']} real, {v8['partly']} partly, {v8['refuted']} refuted; the critic confirmed "
      f"{sum(1 for g in R8['gaps'] if g['severity'] in ('major', 'minor'))} of {len(R8['gaps'])} targets.**", "",
      "The main finding: the length cut had removed hedges earlier rounds established and the data still require, and the",
      "new abstract overclaimed. Among the seventh round's fixes the cut had undone paper7-01 (thinning and visit arrangement),",
      "paper7-04 ('nominally resolved'), paper7-05 ('at the edge of resolution') and paper7-06 ('dataset facts'); the eighth",
      "check restored them, so their dispositions in Addendum 4 describe the current text again.", "",
      "| id | severity | verdict | finding | disposition |", "|---|---|---|---|---|"]
for f in sorted(R8["findings"], key=lambda f: (("critical", "major", "minor").index(f["severity"]), f["id"])):
    L.append(f"| {f['id']} | {f['severity']} | {f['verdict']} | {f['claim'][:200].replace('|', '/').replace(chr(10), ' ')} | {D8.DISPO[f['id']]} |")
L += ["", "### Completeness critic (eighth check)", "", "| # | severity | target | disposition |", "|---|---|---|---|"]
for i, g in enumerate(R8["gaps"]):
    L.append(f"| {i + 1} | {g['severity']} | {g['target'][:160].replace('|', '/')} | {D8.GAPS8[i]} |")
out = os.path.join(os.path.dirname(os.path.dirname(HERE)), "docs", "VERIFICATION_2026-09-12b.md")
open(out, "w").write("\n".join(L) + "\n")
print(f"wrote {os.path.relpath(out)}")
