#!/usr/bin/env python3
"""docs/verification/2026-09-12_findings.json + dispositions_2026_09_12.py -> docs/VERIFICATION_2026-09-12.md."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from dispositions_2026_09_12 import GAPS, ISSUES, MAP  # noqa: E402

R = json.load(open(os.path.join(HERE, "2026-09-12_findings.json")))
F = {f["id"]: f for f in R["findings"]}
mapped = [i for ids in MAP.values() for i in ids]
assert sorted(mapped) == sorted(F), (set(F) - set(mapped), set(mapped) - set(F))
assert len(mapped) == len(set(mapped)), "a finding is mapped twice"
assert set(MAP) == set(ISSUES) and len(GAPS) == len(R["gaps"])
sev = {"critical": 0, "major": 1, "minor": 2}
for h, ids in MAP.items():
    worst = min((F[i]["severity"] for i in ids), key=sev.get)
    assert ISSUES[h][0] == worst, (h, ISSUES[h][0], worst)
counts = {s: sum(1 for f in R["findings"] if f["severity"] == s) for s in sev}
refuted = sum(1 for f in R["findings"] if f["verdict"] == "refuted")
L = ["# Second verification pass of the revision work (2026-09-12)", "",
     "Five independent verifiers (macros, draft logic, new results, code and tests, docs and ledger) re-derived the",
     "corrected state at commit 84216cb and later; each slice's findings were then checked by an adversarial",
     "checker, and a completeness critic examined what nobody had covered. Raw record:",
     "`docs/verification/2026-09-12_findings.json`; dispositions: `docs/verification/dispositions_2026_09_12.py`",
     "(this file is generated by `docs/verification/build_doc_2026_09_12.py`, which asserts that every finding is",
     "mapped to exactly one issue and that each issue's severity is its worst finding's).", "",
     f"**{len(F)} findings: {counts['critical']} critical, {counts['major']} major, {counts['minor']} minor; "
     f"{refuted} refuted.** They group into {len(ISSUES)} issues.", "",
     "## What changed as a result", "",
     "* **The recommended gap-aware checkpoint changed.** Weighting RMDC26's events by rate (which the draft had not",
     "  done or disclosed) puts the combined arm (finite-source single lenses + the measured-season pauses) ahead of",
     "  round 3 at every matched budget; per simulated event the two tie, and on our own held-out the combined arm is",
     "  better. It is now recommended (`ft_fspl5s_seasons_g08.pt`, threshold 0.956) and the operating point, label,",
     "  floor, sub-day, occupancy, between-season and cascade analyses were rerun for it.",
     "* **Two claims were wrong.** The combined arm's extra false alarms are spread over every rho/|u0| bin (not the",
     "  largest ones), and the finite-source physics removed a further part of the false alarms, not most of them.",
     "* **The macro generator is now genuinely fail-closed** (tested), rounds once from counts, and counts every",
     "  checkpoint scored on RMDC26.",
     "* Code: caches keyed by weights, curves stored for local rescoring, onset window end, generation settings",
     "  carried into the memmap, legacy ESPLMag2 regimes, stale-output bug in the fine-tune runner.", "",
     "## Issues", "", "| id | severity | issue | disposition | findings |", "|---|---|---|---|---|"]
for h in sorted(ISSUES):
    s_, t, d = ISSUES[h]
    L.append(f"| {h} | {s_} | {t} | {d} | {', '.join(MAP[h])} |")
L += ["", "## Completeness critic", "", "| # | target | disposition |", "|---|---|---|"]
for i, g in enumerate(R["gaps"]):
    L.append(f"| {i + 1} | {g['target'][:140].replace('|', '/')} | {GAPS[i]} |")
L += ["", "## Not refuted, not changed", "",
      "Nothing was left unaddressed. One item is only partly done: the expansion of 'RMDC26' (H23) is not",
      "documented in any source we found and awaits the RGES-PIT."]
out = os.path.join(os.path.dirname(os.path.dirname(HERE)), "docs", "VERIFICATION_2026-09-12.md")
open(out, "w").write("\n".join(L) + "\n")
print(f"wrote {os.path.relpath(out)}")
