"""Dispositions of the sixth check (2026-09-14): three reviewers of the fifth round's fixes (9e95776..2133a41), their
adversarial checkers, and the completeness critic that had stalled in the fifth verification.

Read by docs/verification/build_doc_2026_09_12b.py, which appends them to docs/VERIFICATION_2026-09-12b.md as a third
addendum and asserts that every finding in 2026-09-14_sixth_findings.json has exactly one disposition."""

DISPO = {
    # paper text and numbers
    "paper6-01": "Fixed. make_figures.py splits the wide-binary misses at dchi2 = 1e6: missed 26-30% of the time in every bin up to "
                 "1e6 and 14% above it (the strongest 19%); the text, evaluation.md and the CHANGELOG say so, guarded on the "
                 "bins quoted (similar rate below, lower rate above).",
    "paper6-02": "Fixed. Data availability: the generator gave the same labels and parameters for a held-out shard at the three "
                 "commits compared (July 21, July 28, September 13), its out-of-range sweeps changed after July, and the stress "
                 "sweeps come back only with run_shard --legacy-oor-mix --legacy-t0-pad.",
    "paper6-03": "Fixed. cascade_gulls.py records a bootstrap interval on each stratum's median-lag difference; the text gives "
                 "+2 d (0 to 4.5 d, at the edge of resolution) and +0.5 d (-0.5 to +2 d, not resolved), guarded; draft and "
                 "REVISION row 10 follow.",
    "paper6-04": "Fixed. Lag differences are macros with a direction-and-interval guard; 'about as frequent' and 'within counting "
                 "noise' are Fisher tests on exact counts; 'almost always called a single lens' has its statistic (95% of "
                 "argmax misses) and guard; the agreement bound is |z| < 2.5.",
    "paper6-05": "Fixed. The figure reference is dropped (the quoted rates are for smaller separations, which the figure does not "
                 "split).",
    "paper6-06": "Fixed ('as disclosed there'; 'about 1% of the cascade-eligible ones, Sec. gulls:cascade').",
    "paper6-07": "Fixed. The class-mix sentence and 'mix-independent' are gone from stress_rescore_local.py; its docstring and the "
                 "run_shard comment state both regeneration deficits.",
    "paper6-08": "Fixed. PROVENANCE: 27% in the quoted four shards (64 against 88 expected), 32% over all 20 (296 against 438, "
                 "regenerated by the fifth verification and not archived).",
    "paper6-09": "Fixed. Data availability names paper/results/stress_report.json for the full-set column and lists that column "
                 "among the exceptions (its 14.9 million per-event predictions are not distributed).",
    "paper6-10": "Fixed (the checker corrected the finding's proposal): all seven populated cells at log q < -4 lie below the median "
                 "(0.51-0.91, 35-130 effective detectable events each), the lowest at -5.5 < log q < -5; guarded.",
    "paper6-11": "Fixed. The rebuild statement exempts the appendix's training settings AND measurements (rates, batches, epochs, "
                 "throughput, hours), read from undistributed logs.",
    # code, artifacts, tests
    "code6-01": "Fixed with paper6-03/paper6-04.",
    "code6-02": "Fixed. Fisher tests and exact counts guard 'about as frequent', 'within counting noise' and 'resolved / not "
                "resolved'; need(stellar share < 5%); the fifth-round code-08 disposition corrected.",
    "code6-03": "Fixed. tests/test_stress_legacy.py pins the counts exactly on macOS arm64 and within 3 per class elsewhere (CI's "
                "Linux); without either switch the counts move by 137 or more, so both switches stay pinned.",
    "code6-04": "Fixed with paper6-07.",
    "code6-05": "Fixed with paper6-08; the bound is stated.",
    "code6-06": "Fixed (|z| < 2.5, below both disclosed deficits), with a perturbation case at z = -3.",
    "code6-07": "Fixed in part. Reused evaluations must carry the checkpoint hash they are filed under; --from-archive refuses to "
                "overwrite the committed artifact. Per-directory stamps were not added (the tiers are done and the back-fill is "
                "disclosed).",
    "code6-08": "Fixed with paper6-02.",
    "code6-09": "Fixed: the abstract's range is guarded to run low to high, with a case.",
    "code6-10": "Fixed (\\bmlTrainFinalEvents).",
    "code6-11": "Fixed. The two legacy attributes are dated by the commit that first wrote them (6865de1); tests/test_gen_settings.py "
                "covers both keys.",
    "code6-12": "Fixed. Cases added for the wide-separation deficit, the matched sub-day rate, the threshold-miss share, the weighted "
                "kept fraction, the canonical-slice check, the F146-only threshold equality and both lag directions, plus every "
                "directional guard the sixth check added (its integrity checks, such as the ablation's grid alignment, have "
                "none); the fifth-round wording (39 cases) corrected to 37.",
    # docs and records
    "docs6-01": "Fixed. The fifth findings, dispositions and second addendum are committed; the CHANGELOG says the critic stalled "
                "and was re-run by this check.",
    "docs6-02": "Fixed with paper6-08.",
    "docs6-03": "Fixed. REVISION row 6 quotes 33% of detectable single lenses at the same 0.25-1 d (the seventh check "
                "corrected the full-range figure to the corrected tier's 37%; 35% is the legacy tier).",
    "docs6-04": "Fixed ('detectable' in README and evaluation.md; README's wide-caustics clause names the 27% deficit).",
    "docs6-05": "Fixed with paper6-07; the make_macros and make_gulls_macros comments updated.",
    "docs6-06": "Fixed (the record regenerated from its generator).",
    "docs6-07": "Fixed in the paper (scan, sub-day, relabelling, floor, between-season combiner, bin occupancy, noise model); "
                "the seventh check added the schedule measurement and the dataset facts, and annotated the CHANGELOG.",
    "docs6-08": "Fixed with paper6-02.",
    "docs6-09": "Fixed with paper6-03/paper6-04 and code6-02.",
    "docs6-10": "Fixed (\\bmlTrainFinalEvents).",
    "docs6-11": "Fixed with code6-12.",
    "docs6-12": "Fixed (the list is headed as targeted tests, mostly out of distribution, and the in-distribution final test).",
    "docs6-13": "Refuted by the checker: README's 38% is F087's loss over all events; 21.6% is over detectable anomalies. Kept.",
}

GAPS6 = [
    "Confirmed and fixed. cascade_reduce.alert_times now anchors strided grids at the season's end (1, 2, ..., 72 d); daily: "
    "1.2% premature at 88.7% detection, two-day 1.0% at 88.4% (was 1.6% at 86.4%, the grid had skipped the 72 d cut); the "
    "text says a coarser grid lowers the premature rate at almost unchanged detection, guarded; every other number unchanged.",
    "Confirmed and fixed. The ablation paragraph says its premature rates use the 7.2 d generator onset grid; all 37 of the "
    "augmented arm's premature alerts at the threshold and 102 of its 111 under argmax fall in the 7.2 d before the grid onset; "
    "alerts earlier than that number 0 vs 32 and 9 vs 45, so the argmax reversal is not established. Computed from the "
    "artifact's per-event lists and guarded.",
    "Confirmed and fixed. The benchmark was rerun on an otherwise idle machine (1,015/s, repeats 1.00-1.03 s; the committed "
    "359/s had been taken under load) and now records the load average, code and checkpoint; the 'could not reproduce, "
    "withdrawn' sentence is replaced; guarded on spread and load.",
    "Confirmed and fixed. gap_matched_density.py has a gap-free regular arm and records empty-bin fractions (uniform 4/9/16%, "
    "nightly >= 60%, regular 0); regular recall 0.617/0.592/0.567; the text says empty bins, not the visit count, make the "
    "thinned schedules collapse (the seventh check added full cadence, 0.94: thinning also costs recall); macros read the artifact directly (the canonical copy is retired); artifact records code and checkpoint.",
    "Confirmed and fixed with paper6-02.",
    "Fixed: 'flags about 9 events without a detectable anomaly for every detectable one' (from the purity alone) and 'a fifth "
    "of the stored events'. Per-event recomputation of the labelling ablation needs the Modal volume (not used).",
    "Fixed: Sec. results adds that the small ECE reflects the 81% of weight below 0.1 and that the weighted mid-range is "
    "over-confident (0.1-0.9: mean score 0.26, anomaly frequency 0.041 weighted, 0.16 stored), close above 0.9; guarded.",
    "Checked fine by the critic; the baselines paragraph now states the comparison set's mixture (half generated as "
    "binaries, nothing subsampled, 4.1% anomaly labels) with a macro cross-checked against the artifact.",
]
