"""Dispositions of the third verification (2026-09-12/13): every finding id -> one issue; ISSUES: id -> (worst severity, issue, disposition)."""

MAP = {
    "I01": ["seeds-and-rule-1", "macros-generator-1", "docs-consistency-1", "repro-ci-1", "seeds-and-rule-3", "seeds-and-rule-7"],
    "I02": ["paper-referee-read-2", "seeds-and-rule-4", "macros-generator-8", "paper-referee-read-3", "docs-consistency-2", "docs-consistency-16"],
    "I03": ["seeds-and-rule-2", "macros-generator-4", "paper-referee-read-13", "docs-consistency-8"],
    "I04": ["seeds-and-rule-5", "macros-generator-5", "docs-consistency-7"],
    "I05": ["seeds-and-rule-6"],
    "I06": ["seeds-and-rule-9", "macros-generator-14", "paper-referee-read-12"],
    "I07": ["seeds-and-rule-10", "macros-generator-13", "docs-consistency-15"],
    "I08": ["seeds-and-rule-8", "docs-consistency-9"],
    "I09": ["macros-generator-2", "docs-consistency-4", "truth-relabel-3"],
    "I10": ["macros-generator-3", "paper-referee-read-15", "docs-consistency-6", "truth-relabel-2"],
    "I11": ["truth-relabel-1", "macros-generator-10"],
    "I12": ["truth-relabel-4"],
    "I13": ["truth-relabel-5"],
    "I14": ["truth-relabel-6"],
    "I15": ["truth-relabel-7"],
    "I16": ["truth-relabel-8"],
    "I17": ["truth-relabel-9"],
    "I18": ["truth-relabel-10"],
    "I19": ["truth-relabel-11"],
    "I20": ["truth-relabel-12"],
    "I21": ["truth-relabel-13"],
    "I22": ["truth-relabel-14", "macros-generator-16"],
    "I23": ["truth-relabel-15", "docs-consistency-12"],
    "I24": ["referee-recompute-1"],
    "I25": ["referee-recompute-2"],
    "I26": ["referee-recompute-3", "paper-referee-read-7", "macros-generator-11"],
    "I27": ["referee-recompute-4", "paper-referee-read-4", "docs-consistency-5", "macros-generator-12", "referee-recompute-9"],
    "I28": ["referee-recompute-5", "paper-referee-read-6"],
    "I29": ["referee-recompute-6", "paper-referee-read-11"],
    "I30": ["macros-generator-6", "referee-recompute-7", "docs-consistency-14"],
    "I31": ["paper-referee-read-5", "referee-recompute-8"],
    "I32": ["referee-recompute-10", "docs-consistency-3", "paper-referee-read-10"],
    "I33": ["referee-recompute-11", "repro-ci-2"],
    "I34": ["referee-recompute-12"],
    "I35": ["paper-referee-read-1"],
    "I36": ["paper-referee-read-8"],
    "I37": ["paper-referee-read-9", "docs-consistency-13"],
    "I38": ["paper-referee-read-14"],
    "I39": ["paper-referee-read-16"],
    "I40": ["paper-referee-read-17"],
    "I41": ["paper-referee-read-18"],
    "I42": ["paper-referee-read-19"],
    "I43": ["paper-referee-read-20"],
    "I44": ["paper-referee-read-21"],
    "I45": ["paper-referee-read-22"],
    "I46": ["macros-generator-7"],
    "I47": ["macros-generator-9"],
    "I48": ["macros-generator-15"],
    "I49": ["docs-consistency-10"],
    "I50": ["docs-consistency-11"],
    "I51": ["repro-ci-3"],
    "I52": ["repro-ci-4"],
    "I53": ["repro-ci-5"],
    "I54": ["repro-ci-6"],
    "I55": ["repro-ci-7"],
}

ISSUES = {
    "I01": ("critical", "Seed rule: the released run's weighted lead (0.024) exceeds the weighted seed range (0.022), so 'does not pass' was false; the verdicts flip with the budget; a three-run range is a weak yardstick",
            "Rewritten: the range is a rough scale, applied per budget and weighting in a new table (Table tab:seeds, bold where a difference exceeds it); verdicts restated from it and each guarded in make_gulls_macros.py; REVISION row 20 and CHANGELOG corrected."),
    "I02": ("critical", "Physics attribution holds per simulated event only; 'removed most of the remaining false alarms' was 45%; 'most of the gain is the extra training' false in mean recall",
            "Attribution rewritten by budget and weighting (extra training: false alarms and low budgets; physics: 11.7%, mean recall, the two largest-ratio bins, per event; nothing weighted, n_eff ~100 and ~50); 'accounts for most of the further reduction'; REVISION row 13 qualified."),
    "I03": ("major", "'Its RMDC26 numbers are the best of the three seeds' true only for planetary recall",
            "Narrowed to planetary recall at every table budget and at its own threshold, with seed 2's lower frozen-threshold false alarms stated; guard extended; README, model card, CHANGELOG, REVISION row 20."),
    "I04": ("major", "Frozen-threshold excess 'by less than its own seeds differ' read per bin fails in the 0.3-1 bin; 'every bin' unguarded",
            "Worded as the overall rate against the seed spread (4.7-7.3%); 'every bin' guarded per event."),
    "I05": ("major", "'Between two seeds they exclude zero' is false for seed 3 vs seed 2",
            "'Can exclude zero', with the s3-s2 pair (includes zero) added to --pairs and quoted."),
    "I06": ("major", "Single-run held-out AP differences (0.010, 0.019) interpreted though the seeds span 0.018",
            "Held-out comparisons state the seed spread: seeds 'tie or exceed' fspl5s with pauses and sit at or just below it clean; the Sec. limits pauses-vs-random-gaps AP comparison qualified."),
    "I07": ("minor", "Budget slack in the Table 7 caption covered unweighted columns only (shipped weighted 5.2% budget is 0.09 points off)",
            "Weighted slack computed and stated."),
    "I08": ("minor", "Seed provenance: 'same code and data' ignores the seed-dependent split and kept epoch; s3 trained at 1c4234f",
            "PROVENANCE, REVISION row 20 and the generator comment now say same pool and recipe, the seed also sets the split and kept epoch (9/5/11), code differs only in comments and truth-gated branches."),
    "I09": ("critical", "LPV truncation 16.4% was a double rounding (408/2,496 = 16.3%)",
            "truth_relabel_impact.py stores counts; macros computed once from counts; 16.3% everywhere."),
    "I10": ("critical", "Pause-relabel 10.5% counted both directions, and the 'label rule' was the full-season-fit approximation",
            "Remeasured against the generator's own rule (refit on the surviving epochs): 9.4% given PSPL although the anomaly survives (relabel on), 2.5% kept NonPSPL unsupported (off); direction guarded."),
    "I11": ("critical", "'The half-day onset reproduces the rule' was true by construction (the reference was the onset itself)",
            "Reference replaced by a single-lens refit at the cut on each binary's rebuilt noise-free curve (reproduces all 858 stored labels; 5 unstable); fixed rule: 2.4% with the half-day onset, 6.4% with 7.2-d, the non-monotone cases; paper and train.py comments say so."),
    "I12": ("major", "'More than half' late PSPL depended on the reference", "About half (49% against the refit reference); guarded as 40-60%."),
    "I13": ("major", "Mixing truth and no-truth caches in to_memmap silently wrote zero truth rows that truth relabelling turns into Flat",
            "convert and convert_selected refuse the mix (tests/test_truth_relabel.py)."),
    "I14": ("major", "AUDIT finding 9 contradicted itself; the truth-bin rule for heavy thinning is ~10% off",
            "Finding 9 rewritten with the refit-reference numbers per augmentation (cadence: legacy 41%, truth bins 10%); train.py docstring no longer calls the approximation adequate for thinning."),
    "I15": ("minor", "Finding 10: single-lens truncation errors are mostly event-chi2 failures, not amplitude", "Reworded with the split (18 of 344 fail the amplitude floor)."),
    "I16": ("minor", "Truth bins: floor(t/72*864) sent 279 of 6,912 epochs one bin early",
            "Binning by a tolerant floor in a tested helper (assemble._ref_bin = epoch k -> k // 8); truth shard regenerated; impact rerun."),
    "I17": ("minor", "The LM refit is chaotic for rare events; part of the non-monotone onset is numerical",
            "Disclosed in the paper (Sec. cascade) and PROVENANCE with measured rates (5 of 858 full-window binary decisions, 0.5% of truncations); the refit is not changed (it would change released labels)."),
    "I18": ("minor", "Self-consistency checks started from the stored label and could not catch a rule that fails to demote",
            "Two-sided in the script and the test (from the generator class; every stored label reproduced)."),
    "I19": ("minor", "A truncation test exercised only the no-onset fallback", "Commented as the fallback test; the onset rule has its own test."),
    "I20": ("minor", "--truth-bins without --onset-resolution-days 0.5 silently kept the 7.2-d onset", "run_shard warns; train warns when the cache's onset grid is coarser than half a day."),
    "I21": ("minor", "Truth relabelling hard-coded the 0.02-mag floor", "train refuses a truth cache generated at another floor."),
    "I22": ("minor", "Artifacts stamped with a dirty tree before the code they depend on; unused imports; tables not compared in the test",
            "truth_relabel_impact.json regenerated at a clean commit; referee_round.json re-reduced at one from cached intermediates made at earlier commits (PROVENANCE lists them; fourth verification); imports removed; the complete-inputs test compares every output."),
    "I23": ("minor", "AUDIT ledger still listed findings 8-10, figures and Zenodo as open; 35.6 -> 11.7%", "Ledger updated (decided and done; 11.6%)."),
    "I24": ("critical", "The floor arms are partly the same events (21.6% / 4.5% shared), not independent draws",
            "'Partly overlapping draws' with the measured overlap (floor_overlap in the artifact); runner docstring, CHANGELOG, REVISION section 2."),
    "I25": ("major", "The colour effect is lower variable-class precision (flat called periodic, single lenses called eruptive), not worse rejection of variables",
            "Paragraph rewritten with precision and recall; directions guarded (precision down, recall unchanged, no more variables sent to microlensing)."),
    "I26": ("major", "The colour fine-tune contrast rested on single runs and the kept epoch; it vanishes one epoch later",
            "Final-epoch evaluations added; the claim now rests on the audited fine-tune's drop on the old photometry (kept and last epoch) and states that the audited-photometry difference disappears at the last epoch."),
    "I27": ("major", "Abstract and Conclusion called the three-band every-class scan 'the same way' and quoted the test set's prevalence",
            "Scan run also with F146 alone; abstract and Conclusion name the bands, the simulated prevalence and 'detectable anomalies', and give the F146-only purity."),
    "I28": ("major", "In-house 0.7% was the raw fraction; the RMDC26 comparison mixed checkpoint, bands, weighting and units",
            "Reweighted and raw both given, generated single lenses and demoted binaries split; the RMDC26 comparison is now like for like (recommended checkpoint, F146, frozen threshold on our generated single lenses); RMDC26 figures labelled per event / weighted, per 1,000 single lenses per day."),
    "I29": ("major", "Referee-round per-event inputs not distributed; Data availability silent on the new artifacts",
            "Per-event inputs archived with hashes (validation/referee_round_archive/, --archive); Data availability names referee_round.json and truth_relabel_impact.json; dirty-tree fine-tunes and MPS non-determinism disclosed."),
    "I30": ("major", "AP and F1 were on the evaluator's 80% split while completeness and purity used every event",
            "All four on every event (all_events block); the evaluator's split values kept alongside."),
    "I31": ("major", "'Test shards' 90-91 include ~15% of the rows the frozen threshold was chosen on",
            "Called shards of the held-out pool, with the measured share (threshold_selection_overlap)."),
    "I32": ("major", "Docs and the fig. cascade caption still said no alert-burden or colour measurement exists",
            "README, model card, usage, evaluation, pipeline docs and the caption point to the every-class scan and the colour result."),
    "I33": ("minor", "Colour fine-tunes: best epoch kept, not three epochs; learning rates", "Described as up to three epochs keeping the best; the training-recipe paragraph gives the learning rates."),
    "I34": ("minor", "Prior-shift purity also holds the non-anomalous mix fixed", "Stated."),
    "I35": ("critical", "Table 5 note still said the Paczynski fit used a thinned 800-epoch subset", "Corrected: all methods at full cadence."),
    "I36": ("major", "The Introduction did not mention the RMDC26 test", "A fourth contribution added."),
    "I37": ("major", "Conclusion: 'raised in review' and 'three tests' inaccurate; streaming calibration dropped from the open tests",
            "Rewritten against the submitted version's list; a disjoint-prefix streaming threshold restored to the remaining tests."),
    "I38": ("minor", "'Delays, never advances' contradicted by the stored-truth check", "'Almost always delays'."),
    "I39": ("minor", "Abstract length and unlabelled weightings",
            "'Per simulated event' and 'of the planetary events we checked' added; the abstract is ~360 words against ~265 submitted (A&C's limit could not be checked offline; flagged to the author)."),
    "I40": ("minor", "Detection comparison mixed checkpoint and simulator", "Said so."),
    "I41": ("minor", "'No operating threshold was chosen on it' while matched-budget thresholds are set on RMDC26", "'No deployed operating threshold'; the reporting thresholds are named."),
    "I42": ("minor", "The list of schedule differences omitted the within-season pauses", "Added."),
    "I43": ("minor", "Audited F087 saturation used at the 46.8-s exposure", "Refuted: the audited limit is relative to F146 at equal exposure; no change."),
    "I44": ("minor", "Unlabelled Wilson intervals; 'vestigial' chi2 cuts vs RMDC26's 26% failing the cut", "Intervals labelled; 'vestigial for our error model', and the RMDC26 labels section says the cut binds with GULLS' errors."),
    "I45": ("minor", "Stray space in corporate-author citations; per-event bins unlabelled; '1000' vs '1,000'",
            "build.sh strips the bst's leading space; caption says per simulated event; count macros use separators."),
    "I46": ("major", "Fail-closed tests did not exercise the new guards", "Value-perturbation cases added (floor direction, stream variable alert, colour recall, seed order, weighted physics, truncation late share, missing seed pair and refit reference)."),
    "I47": ("minor", "--list-inputs omitted the two directly read JSONs", "Both read through load(); a test asserts every listed input is hashed in the manifest."),
    "I48": ("minor", "Directional sentences without guards", "Guards added for the ones this round touched (every bin, 2S2L 'by more', abstract 'raises', 'barely moves', 'largely intact', pause-relabel directions, colour directions)."),
    "I49": ("minor", "REVISION housekeeping (mean 0.538, 'seventeen rows', row 19 file name, Zenodo)", "Fixed."),
    "I50": ("minor", "VERIFICATION_2026-09-12 H23 and notebook 01's 'a fifth of the selected events' stale", "Notebook sentence corrected; this record supersedes H23 (the expansion is from the dataset card)."),
    "I51": ("minor", "Committed rendered draft stale", "Regenerated; CI now compares regenerated macros, tables and rendered draft with the committed files."),
    "I52": ("minor", "The documented --scores clone command did not run", "The artifact records command_from_clone; README and REVISION point to it."),
    "I53": ("minor", "CI gaps: generated outputs not compared, 'Label(s) may have changed' not checked", "Both added to paper-build.yml."),
    "I54": ("minor", "Git history contains the AWS account id (b8b1a86) and a personal e-mail (69b1aa9)", "Not changed: rewriting published history is the author's decision (reported)."),
    "I55": ("minor", "Artifacts embed absolute local paths", "Noted; kept as provenance."),
}
GAPS = [
    "Confirmed and fixed. The 14.9M-event stress suite was scored with the stage-5 checkpoint (aws/ud_bineval.sh), the released model's predecessor. The full suite is on S3; validation/stress_rescore_local.py regenerates the first shards of each quoted tier with the suite's seeds (and its original out-of-range class mix, run_shard --legacy-oor-mix) and scores the same events with both checkpoints. The paper now quotes the released checkpoint on that subset, with the suite's stage-5 values alongside (Table tab:stress), and says which model scored the suite; stage 5 on the subset reproduces the suite (macro-F1 0.927 vs 0.927, median difference 0.012). The released model's natural macro-F1 is 0.919 (its held-out 0.919). The 0.524 figure is confirmed not to be a single-lens recall (38% of the weighted PSPL labels are demoted binaries): sub-day single lenses are classified PSPL 0.274 and called anomalies 71% of the time (37% above the frozen threshold); the paper now says so, and that stage 6 trained on the edges of three of the sweeps.",
    "Confirmed and fixed. Sec. limits no longer calls the low-q regime barely populated (it is a stage-4 training pool) and states the stage-6 coverage of the sweeps. The appendix now describes the six-stage warm-start chain from the stage logs (base: batch 512, learning rate 3e-4, factor 2 on the anomaly class; stages 2-6: learning rates 1.2e-4, 3e-5, 5e-5, batch 384 from stage 4, factor 1; stage 6: 1.9M events, 6 epochs, zero-based epoch 4 released; ~22 h in total); paper/canonical_numbers.json infra corrected (batch 256 and 5 epochs had described the base run's defaults).",
    "Not checkable here (the training caches are on S3); AUDIT finding 14 stays open and is listed in the ledger.",
    "Addressed: after the fixes the final state was checked again by a fourth verification (addendum below); macros, tables and rendered draft are now compared with the committed files in CI.",
    "Kept: 0.144 is the grid threshold's value (the budget sits 0.09 points off because of a tie block); the caption now states the weighted slack.",
    "Checked in the fourth verification (addendum below): see its findings cascade-1 to cascade-7 and the ledger findings.",
    "Addressed where the paper interprets in-house single-run AP differences: the pauses-vs-random-gaps comparison (0.921 vs 0.911, clean 0.948 vs 0.952) is now stated to be within the 0.018 seed spread; other in-house comparisons (cadence, gap augmentation vs shipped) are either far larger or already called unresolved.",
    "Partly: the artifacts predate no checkpoint change after stage 6 (all committed 2026-08-04 or later, after stage 6 shipped on 2026-07-26), so stage 6 is likely but not recorded; noted in PROVENANCE, not changed.",
    "Flagged to the author: the abstract is ~360 words (submitted ~265); A&C's limit was not checked offline.",
    "Not checked (needs the current Roman calibration tables); the audited constants are as recorded in pipeline/photometry.py with their sources.",
    "Checked in the fourth verification (addendum below): see its findings cascade-1 to cascade-7 and the ledger findings.",
    "Addressed in the text (the seed also sets the split and the kept epoch) and in PROVENANCE and REVISION row 20.",
]
