"""Dispositions for the second verification pass (2026-09-12): issue groups H01-H49 and the finding -> issue map.

Every one of the 74 findings in 2026-09-12_findings.json maps to exactly one issue (build_doc_2026_09_12.py asserts
it). Severity is the highest of the mapped findings. None was refuted by the adversarial checkers."""

ISSUES = {
 "H01": ("critical", "Combined arm's extra false alarms said to be 'mostly in the largest-ratio bins' (draft, ledger row 14)",
         "Fixed: 39 of the 468 extra flags are in the two largest bins; the draft now says 'in every rho/|u0| bin' and row 14 says most extra flags are at rho/|u0| < 1."),
 "H02": ("critical", "Physics credited with 'a large part' of the residual false alarms; 'point-like bins barely change'",
         "Fixed: draft, ledger row 13, CHANGELOG and G14 now say the extra training did most of it; the physics lowers false alarms in every bin (-14% to -44%), most in rate in the largest bins, part of it where finite size cannot matter; weighted, its recall gain is unresolved."),
 "H03": ("critical", "All RMDC26 rates were per simulated event without saying so; conclusions depend on it",
         "Fixed: weighted blocks, per-checkpoint operating points and paired bootstrap differences in transfer_tradeoff_all.json; two weighted columns in Table gulls; a weighting paragraph in Results; the timescale mismatch disclosed; the recommendation re-decided under both weightings (the combined arm, which ties per event and leads weighted, is now recommended) and every downstream analysis rerun for it."),
 "H04": ("major", "Macro generator not fail-closed: tables written before later checks; four silent fallbacks",
         "Fixed: outputs built in memory and written only after every check; need() replaces the fallbacks; 'FATAL' rejected as a value; duplicate macros rejected. tests/test_macros_fail_closed.py mutates six inputs and checks that nothing is written."),
 "H05": ("major", "Checkpoint count (8, then 9) excluded five scored schedule arms; documents said 7",
         "Fixed: \\bmlGullsNcheckpoints counts every fine-tune scored on RMDC26 (14); G44 and the first-pass summary updated."),
 "H06": ("major", "Double rounding: mean recall 0.538 (exact 0.5385 -> 0.539), colour undetectable 0.170 (383/2260 = 0.169), several ledger and section-1 values",
         "Fixed: unrounded mean recall stored and used; colour and occupancy counts stored; between-season percentages from counts; ledger rows 3, 5, 13 and section 1 values rounded once."),
 "H07": ("major", "The 0.014-0.023 'seed spread' is two runs of one recipe on different pools with the same seed",
         "Fixed: described as a pool spread in the draft and ledger; its weighted analogue (0.005) added; the text no longer calls it run-to-run or seed variation."),
 "H08": ("minor", "'generalises poorly to the other five (0.568)' but 0.568 is over all six seasons",
         "Fixed: 'scores only 0.568 across the six seasons, its own included'."),
 "H09": ("minor", "Reversed range '23--21%'", "Fixed: min/max range macros for the bright-baseline and blend-fraction ranges."),
 "H10": ("minor", "Caption said the budgets equal two checkpoints' rates", "Fixed in 0988a0d ('close to ... 5.2% and 11.6%')."),
 "H11": ("minor", "Typed data-derived numbers in a file that claimed none",
         "Fixed: season shortfall, recurring pause days and the pooling sensitivity are macros (new dataset facts); the header now says typed numbers are method constants only."),
 "H12": ("minor", "Partial-occupancy share quoted as 34% (minimum season) vs 35% elsewhere; colour 2/3 share '45%'",
         "Fixed: median season (35%) in the draft; ledger row 15 gives 34.5-35.3% and 36-47% (about 41%) for colour bins."),
 "H13": ("minor", "Table captions: gap-table first row is not a fine-tune; missing tablenotemark; omitted bins unstated; wrong section reference",
         "Fixed: captions reworded, tablenotemark added, the two omitted rho/|u0| bins named, the relabel reference points to Sec. limits."),
 "H14": ("minor", "schedule_finetune.json lacked n_true_class_binaries and recorded the code at write time",
         "Fixed: runner records code_at_start and code_at_write; the reduce was rerun from cached results (numbers unchanged, 28,419 now stored)."),
 "H15": ("minor", "render_draft.py fails on a clean clone (paper_macros.tex is generated and gitignored)",
         "Fixed: clear error with the build order (make_figures, make_macros, make_gulls_macros, render_draft)."),
 "H16": ("major", "Cascade three-band comparison used the whole in-house scan against planetary strata",
         "Fixed: the draft says in-house three-band numbers exist only for the whole, mostly stellar, scan and are not comparable with the planetary strata; ledger row 10 likewise."),
 "H17": ("major", "Discussion: 'recovers most' of the between-season events (scorability, not recovery)",
         "Fixed: 'makes most of the former scorable ... but at the frozen threshold flags only 20% of their planetary events'."),
 "H18": ("major", "'a fifth of the selected events' pools classes, mixes eligible/selected, omits RMDC26's t0 concentration",
         "Fixed: class split (27% of single lenses, 9-10% of planetary events between seasons; 23% and 4-9% in low-cadence seasons), 'eligible', and the concentration of catalogue peaks in high-cadence seasons (64-71% in 25% of the span), all from rmdc26_dataset_facts.json."),
 "H19": ("major", "'the gap-aware checkpoint of Sec. gulls' in [B] meant g08e12 in Sec. gulls",
         "Fixed: [B] now points to 'the recommended checkpoint'; g08e12 is 'the gap-augmented checkpoint' throughout the draft."),
 "H20": ("major", "Clean-data cost stated in macro-F1 for one arm and AP for the other",
         "Fixed: average precision for both, with the direction stated."),
 "H21": ("major", "The paper's own single-slice threshold (0.931 for fspl5s) was not disclosed",
         "Fixed: the operating-point paragraph gives the single slice's threshold and its RMDC26 rates for the recommended checkpoint (0.946: 3.2%, 0.32) and why the full pool is used."),
 "H22": ("minor", "'limited by significance rather than amplitude' not supported by a stored 2-D breakdown",
         "Fixed: 'tracks significance more closely than amplitude' (the verifier's 2-D check supports it)."),
 "H23": ("minor", "Citations: GBTDS citations dropped from [B]; RMDC26 not cited or expanded at first use; baseline offset in main text",
         "Partly fixed: GBTDS citations restored, RGES-PIT cited at first use in [B], the baseline remark removed from the text. The expansion of 'RMDC26' is not documented anywhere we could find; the draft names it 'the RMDC26 release' and the [F] block asks the author to confirm it with the RGES-PIT."),
 "H24": ("minor", "Hedges: 'because' in the abstract; untested wing-season explanation; sub-day 'not as microlensing'; prevalence and weighting undefined",
         "Fixed: 'mostly because'; '(we did not test why)'; sub-day now 'most probable class mostly PeriodicVar, 15% microlensing' and compared with in-support rates; purity stated as single-lens contamination at a stated prevalence."),
 "H25": ("major", "Ledger row 9 quoted an in-season comparator (0.48 / 0.57) that no artifact holds",
         "Fixed: 0.50 / 0.58 for fspl5s and 0.53 / 0.62 for the recommended checkpoint, from the relabel artifact."),
 "H26": ("minor", "A fourth difference of the combined arm (finite-source visible amplitude in the truncation augmentation) not named",
         "Fixed: the draft and row 14 name it; the smooth-function control carries it too, so 'these two changes together do nothing measurable'."),
 "H27": ("major", "floor_sensitivity.json's calibrated block was at the superseded 0.949 and not reproducible by the committed script",
         "Fixed: regenerated (label side unchanged); calibrated blocks now store their threshold; command recorded; PROVENANCE row updated."),
 "H28": ("minor", "seasonsocc artifact labelled 'seasons'; calibration eval directories renamed after evaluation",
         "Fixed: label corrected by hand with a note field; renames documented in PROVENANCE (logits reproduce exactly)."),
 "H29": ("minor", "train.py docstring quoted 5.4% -> 4.4% for occupancy; run_shard comment implied a fixed pool",
         "Fixed: 4.9% -> 3.6% with the artifact named; the control is 'a different random realisation of the same priors'."),
 "H30": ("minor", "Generation settings (onset, noise, regime, ESPL function) stopped at the raw shards",
         "Fixed: run_shard writes espl_function; build_cache and to_memmap carry gen_settings into the cache attrs and meta.json; tests/test_gen_settings.py."),
 "H31": ("minor", "fspl_finetune_local.py reused stale eval/RMDC26 outputs after a retrain; provenance hard-coded ESPLMag",
         "Fixed: a stamp change deletes the eval dir, rows and summaries; espl_function derived from the prefix."),
 "H32": ("minor", "transfer_subday.json lacked calibrated entries the committed script now writes",
         "Fixed: regenerated with the recommended checkpoint added (existing values unchanged); command recorded."),
 "H33": ("minor", "_visible_amplitude comment said binaries never reach the finite-source branch",
         "Fixed: comment names the fspl5 regimes (binary rho up to 0.1)."),
 "H34": ("minor", "Fine onset grid never tested the window end when res does not divide 72 d",
         "Fixed: the window end is the last cut; regression test added."),
 "H35": ("minor", "Cascade and between-season caches keyed by model name, not weights",
         "Fixed: manifests bind names to weight hashes and refuse collisions; the cascade reducer merges per-model scan files; the between-season extractor stores curves and rescores missing models locally."),
 "H36": ("minor", "CI extras lacked pyarrow/pandas, so the scores-route test always skipped",
         "Fixed: added to the dev extras."),
 "H37": ("major", "The legacy ESPLMag2 flag could not be set without editing code; the Reproduce block rebuilt a different pool",
         "Fixed: regimes fspl5s_legacy{,_highmag} (same seeds, ESPLMag2); runner docstring and Reproduce block updated."),
 "H38": ("major", "CHANGELOG second entry repeated three withdrawn phrasings",
         "Fixed: 20.1% of NonPSPL-labelled events (7.4% of binaries); 'first season's seven pauses'; 'no anomaly our policy would claim within one season'."),
 "H39": ("major", "PROVENANCE said the quantised onset affects only post-submission fine-tunes",
         "Fixed: it is shared by the shipped model's training labels (disclosed in the paper)."),
 "H40": ("minor", "13 old transfer artifacts carry the obsolete 'NOT A TRANSFER MEASUREMENT' status string",
         "Documented in PROVENANCE (artifacts left as written)."),
 "H41": ("minor", "Section-1 numbers (6 of 89,919; 0.4%) exist only in the first pass's notes",
         "Fixed: attributed to docs/verification/2026-09-11_findings.json, the 0.4% labelled a proxy measured on the cadence pool."),
 "H42": ("minor", "Superseded ledger's closing paragraph read as current; blank lines broke its table",
         "Fixed: labelled superseded; table joined."),
 "H43": ("minor", "Stale comments and docstrings (first-pass G28 fixes not made)",
         "Fixed: gulls_transfer.py, gap_sensitivity.py, train.py, binml/gulls.py, multi_season.py, tests/test_gap_augmentation.py."),
 "H44": ("minor", "Section 1: 'no other class lost' for fspl_g08 (LongPeriodVar lost 0.005-0.013)", "Fixed."),
 "H45": ("minor", "Status-table row cited the superseded fspl_g08 calibration file", "Fixed: cites gapped_threshold_fspl_g08_seasons.json."),
 "H46": ("minor", "Missing bibliography entries tracked only in a draft comment", "Fixed: rows in the REVISION status table (author action)."),
 "H47": ("minor", "Ledger/draft inconsistencies (0.325 vs 0.326, 0.298 vs 0.299, 'Timing transfers')",
         "Fixed with H06 and H16; row 10 now says premature alerts stay rare and alerts come later."),
}

MAP = {
 "H01": ["macros-1", "draft-logic-1", "new-results-1", "docs-ledger-1"],
 "H02": ["draft-logic-2", "new-results-2", "macros-12"],
 "H03": ["draft-logic-3"],
 "H04": ["macros-2", "code-tests-1", "draft-logic-15"],
 "H05": ["macros-3", "draft-logic-10", "code-tests-2", "docs-ledger-10"],
 "H06": ["macros-4", "docs-ledger-2", "new-results-5", "docs-ledger-6"],
 "H07": ["macros-5", "new-results-11"],
 "H08": ["macros-6"],
 "H09": ["macros-7"],
 "H10": ["macros-8"],
 "H11": ["macros-9", "draft-logic-14"],
 "H12": ["macros-10", "new-results-12", "docs-ledger-11"],
 "H13": ["macros-11", "draft-logic-13"],
 "H14": ["macros-13", "new-results-6"],
 "H15": ["macros-14", "code-tests-14"],
 "H16": ["draft-logic-4"],
 "H17": ["draft-logic-5", "new-results-3"],
 "H18": ["draft-logic-6"],
 "H19": ["draft-logic-7"],
 "H20": ["draft-logic-8"],
 "H21": ["draft-logic-9"],
 "H22": ["draft-logic-11"],
 "H23": ["draft-logic-16"],
 "H24": ["draft-logic-17"],
 "H25": ["new-results-4", "docs-ledger-3"],
 "H26": ["new-results-7"],
 "H27": ["new-results-8", "code-tests-3", "docs-ledger-7"],
 "H28": ["new-results-9", "code-tests-8"],
 "H29": ["new-results-10", "code-tests-9"],
 "H30": ["code-tests-5"],
 "H31": ["code-tests-6"],
 "H32": ["code-tests-7"],
 "H33": ["code-tests-10"],
 "H34": ["code-tests-11"],
 "H35": ["code-tests-12"],
 "H36": ["code-tests-13"],
 "H37": ["code-tests-4"],
 "H38": ["docs-ledger-4", "code-tests-15"],
 "H39": ["docs-ledger-5"],
 "H40": ["docs-ledger-8"],
 "H41": ["docs-ledger-9"],
 "H42": ["docs-ledger-12"],
 "H43": ["docs-ledger-13"],
 "H44": ["docs-ledger-14"],
 "H45": ["docs-ledger-15"],
 "H46": ["docs-ledger-16"],
 "H47": ["draft-logic-12"],
}

GAPS = {  # the completeness critic's 12 extra checks: what each found and what was done
 0: "No problem: every committed score reproduces from the rows; FA counts match (g08e12 off by one event at 4 d.p. storage).",
 1: "No problem for the attribution; the occupancy nuance (single lenses read occupancy as anomaly only for fspl5s) is consistent with row 15.",
 2: "Strengthens H16: per-stratum three-band numbers diverge in-house (Neptune detection falls); handled by H16.",
 3: "Position dependence of the single-gap cost: README, model card, REVISION section 1, the draft and gap_sensitivity.py now say the gap sits at day 43 and the cost depends on position.",
 4: "No problem: 4-d.p. storage moves no macro.",
 5: "Adds evidence to H07 (same-seed training is nearly deterministic here; seed variance unmeasured).",
 6: "Noise model computed from truth cache v1: ledger row 5 notes the v2 values (2.67x, 7.6x); conclusions unchanged.",
 7: "No problem: the partial bins are colour visits (78%) and pause edges; handled with H12.",
 8: "Stale code comments: fixed under H43.",
 9: "No problem: no train/held-out seed overlap.",
 10: "No problem: catalogue-baseline offset 0.471 mag reproduces (now stored in rmdc26_dataset_facts.json).",
 11: "No problem at the default worker count; the one-per-thousand statement traces to one seed.",
}
