#!/usr/bin/env python3
"""canonical_numbers.json (+ outputs/figures_stats.json) -> paper_macros.tex.

Every number in paper.tex is a \\bml* macro defined here, so the manuscript can never drift
from the evaluation artifact. Run after make_figures.py:  python make_macros.py
"""
import json, os, sys

import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))
# Every artifact this generator reads goes through _jload, so `--list-inputs` can name them (each must be hashed in
# paper/results/MANIFEST.json; tests/test_validation_and_invariants.py checks it). --list-inputs writes nothing.
LIST_INPUTS = "--list-inputs" in sys.argv[1:]
INPUTS = []


def _jload(path):
    path = os.path.normpath(path)
    if path not in INPUTS:
        INPUTS.append(path)
    with open(path) as fh:
        return json.load(fh)



cn = _jload(os.path.join(HERE, "canonical_numbers.json"))
fs_path = os.path.join(HERE, "outputs", "figures_stats.json")
if not os.path.exists(fs_path):
    # FAIL CLOSED. figures_stats.json is generated by make_figures.py and gitignored; loading `{}`
    # in its absence would let every `if key in fs` block below silently skip its macros.
    raise SystemExit(f"FATAL: {fs_path} missing; run paper/make_figures.py first")
fs = _jload(fs_path)

L = []
def cmd(name, value):
    # Thousands separators must be {,} not ",": several macros are used inside $...$, where a bare
    # comma is math punctuation and typesets with a trailing space ("505, 479" in the abstract).
    # NaN/inf guard: a NaN in any source artifact would otherwise typeset as the literal "nan".
    if isinstance(value, float) and not math.isfinite(value):
        raise SystemExit(f"FATAL: macro {name} is {value!r}; a source artifact holds a non-finite value")
    if isinstance(value, str) and value.strip().lower() in ("nan", "inf", "-inf", "none"):
        raise SystemExit(f"FATAL: macro {name} formatted as {value!r}")
    L.append(r"\newcommand{\%s}{%s}" % (name, str(value).replace(",", "{,}")))

def pct(x):   return f"{100*x:.1f}"
def two(x):   return f"{x:.2f}"
def three(x): return f"{x:.3f}"

h = cn["headline"]
cmd("bmlNtest", f"{cn['test']['n_events']:,}")
cmd("bmlNpool", f"{cn['test']['n_pool']:,}")
cmd("bmlNval", f"{cn['test']['n_val']:,}")
cmd("bmlCompleteness", three(h["completeness_at_purity"]))
cmd("bmlCompletenessPct", pct(h["completeness_at_purity"]))
cmd("bmlCompletenessLo", three(h["completeness_ci_lo"]))
cmd("bmlCompletenessHi", three(h["completeness_ci_hi"]))
cmd("bmlPurity", three(h["purity_achieved"]))
cmd("bmlPurityTarget", two(h["purity_target"]))
cmd("bmlAP", three(h["average_precision"]))
cmd("bmlMacroF", three(h["macro_f1"]))

for c, v in cn["per_class"].items():
    if c == "note":
        continue
    cmd(f"bml{c}R", three(v["recall"]))
    cmd(f"bml{c}P", three(v["precision"]))
    cmd(f"bml{c}F", three(v["f1"]))

cmd("bmlNonpsplPhysP", three(cn["nonpspl_physical_precision"]))
cmd("bmlSliceStrongAnom", three(cn["nonpspl_recall_strong_anomaly"]))

sup = cn["per_class_support"]
for c in ["Flat", "PSPL", "NonPSPL", "PeriodicVar", "LongPeriodVar", "Eruptive"]:
    cmd(f"bmlSup{c}", f"{sup[c]:,}")

# The labelling surgery is derived on the final test by make_figures.py (fifth verification: the hand-copied
# canonical block was the whole pool's, and unweighted over the subsampled stored events).
for _k in ("relabelled_pct", "nonpspl_kept_pct", "nonpspl_to_pspl_pct", "lpv_to_flat_pct", "nonpspl_kept_pct_w", "nonpspl_to_pspl_pct_w"):
    if _k not in fs:
        raise SystemExit(f"FATAL: figures_stats lacks '{_k}'; rerun make_figures.py")
cmd("bmlRelabelled", f"{fs['relabelled_pct']:.1f}")
cmd("bmlNonpsplKept", f"{fs['nonpspl_kept_pct']:.1f}")
cmd("bmlNonpsplToPspl", f"{fs['nonpspl_to_pspl_pct']:.1f}")
cmd("bmlLpvToFlat", f"{fs['lpv_to_flat_pct']:.1f}")
cmd("bmlNonpsplKeptW", f"{fs['nonpspl_kept_pct_w']:.1f}"); cmd("bmlNonpsplToPsplW", f"{fs['nonpspl_to_pspl_pct_w']:.1f}")

# CASCADE: read straight from the tracked artifact, never from a hand-copied block. If the
# artifact is missing or its schema changed, FAIL rather than emit stale numbers -- prose/artifact
# drift is exactly how the withdrawn 42%->9% claim survived in the manuscript.
_casc_path = os.path.join(os.path.dirname(HERE), "validation", "cascade_reproduce_result.json")
if not os.path.exists(_casc_path):
    raise SystemExit(f"FATAL: {_casc_path} missing; run validation/cascade_trace.py then "
                     f"validation/cascade_reduce.py")
cas = _jload(_casc_path)
for _k in ("n_eligible", "detection_fraction", "premature_rate_of_eligible",
           "premature_ci_of_eligible", "premature_rate_of_detected", "median_lag_detected_days",
           # the two medians must BOTH exist: reporting only the all-detections median as if it
           # were the post-onset delay was an arithmetic error in an earlier revision
           "median_lag_non_premature_days", "n_lag_non_premature", "sensitivity"):
    if _k not in cas:
        raise SystemExit(f"FATAL: cascade artifact lacks '{_k}'; regenerate it "
                         f"(schema changed -- do not hand-edit the JSON)")
cmd("bmlCascN", f'{cas["n_eligible"]:,}')
cmd("bmlCascDetFrac", pct(cas["detection_fraction"]))
cmd("bmlCascPrematurePct", pct(cas["premature_rate_of_eligible"]))
cmd("bmlCascPrematureLo", pct(cas["premature_ci_of_eligible"][0]))
cmd("bmlCascPrematureHi", pct(cas["premature_ci_of_eligible"][1]))
cmd("bmlCascPrematureOfDet", pct(cas["premature_rate_of_detected"]))
# NAME THE POPULATION IN THE MACRO NAME. \bmlCascMedianLagAll is over ALL detections and mixes in
# the negative lags of premature alerts; \bmlCascMedianLagNonPrem is the post-onset delay.
cmd("bmlCascMedianLagAll", f'{cas["median_lag_detected_days"]:+.1f}')
cmd("bmlCascMedianLagNonPrem", f'{cas["median_lag_non_premature_days"]:+.1f}')
cmd("bmlCascNnonPrem", str(cas["n_lag_non_premature"]))
cmd("bmlCascNdet", f'{cas["n_detected"]:,}')
cmd("bmlCascCensored", str(cas["n_censored"]))

_sen = cas["sensitivity"]
# ONSET DEFINITION bracket. The premature rate moves by a factor of ~20 across these, which is far
# more than any modelling choice moves it, so the paper reports the range rather than a number.
_od = _sen["onset_definition"]
cmd("bmlCascPrematurePersistPct", pct(_od["persistent_detectable"]["premature_rate_of_eligible"]))
cmd("bmlCascPrematurePersistLo",
    pct(_od["persistent_detectable"]["premature_ci_of_eligible"][0]))
cmd("bmlCascPrematurePersistHi",
    pct(_od["persistent_detectable"]["premature_ci_of_eligible"][1]))
cmd("bmlCascMedianLagPersist",
    f'{_od["persistent_detectable"]["median_lag_non_premature_days"]:+.1f}')
cmd("bmlCascOnsetShift", f'{_od["median_coarse_minus_first_days"]:.1f}')
cmd("bmlCascNonMonotone", str(_od["n_non_monotone"]))
cmd("bmlCascCoarsePrematurePct", pct(_sen["onset_coarse_7p2d"]["premature_rate_of_eligible"]))
cmd("bmlCascCoarseMedianLagAll",
    f'{_sen["onset_coarse_7p2d"]["median_lag_detected_days"]:+.1f}')
cmd("bmlCascCoarseMedianLagNonPrem",
    f'{_sen["onset_coarse_7p2d"]["median_lag_non_premature_days"]:+.1f}')
_g = _sen["evaluation_grid_days"]
cmd("bmlCascGridHalfPct", pct(_g["0.5"]["premature_rate_of_eligible"]))
cmd("bmlCascGridOnePct", pct(_g["1.0"]["premature_rate_of_eligible"]))
cmd("bmlCascGridTwoPct", pct(_g["2.0"]["premature_rate_of_eligible"]))
cmd("bmlCascGridOneDet", pct(_g["1.0"]["detection_fraction"]))
cmd("bmlCascGridTwoDet", pct(_g["2.0"]["detection_fraction"]))
# "a coarser grid lowers the premature rate at almost unchanged detection" (grids end at the season's end)
if not (_g["2.0"]["premature_rate_of_eligible"] <= _g["1.0"]["premature_rate_of_eligible"]
        < _g["0.5"]["premature_rate_of_eligible"]):
    raise SystemExit("FATAL: 'coarsening the grid lowers the premature rate' no longer holds")
if max(abs(_g[k]["detection_fraction"] - _g["0.5"]["detection_fraction"]) for k in ("1.0", "2.0")) >= 0.01:
    raise SystemExit("FATAL: 'at almost unchanged detection' no longer holds for the coarser grids")
if not (_g["0.5"]["median_lag_non_premature_days"] < _g["1.0"]["median_lag_non_premature_days"]
        <= _g["2.0"]["median_lag_non_premature_days"]):
    raise SystemExit("FATAL: 'at the price of later alerts' no longer holds for the coarser grids")
_p2 = _sen["persistence_consecutive_crossings"]["2"]
cmd("bmlCascPersistTwoPct", pct(_p2["premature_rate_of_eligible"]))
cmd("bmlCascPersistTwoDet", pct(_p2["detection_fraction"]))
_mb = _sen["bands"]["all_three_bands"]
cmd("bmlCascMultibandPct", pct(_mb["premature_rate_of_eligible"]))
cmd("bmlCascMultibandDet", pct(_mb["detection_fraction"]))
cmd("bmlCascMultibandMedianLag", f'{_mb["median_lag_non_premature_days"]:+.1f}')
cmd("bmlCascArgmaxPct", pct(_sen["argmax_rule"]["premature_rate_of_eligible"]))

# The alert-policy table is GENERATED from the same artifact rather than typed into paper.tex.
# Fifteen numbers in a hand-written tabular is fifteen chances to update the analysis and forget
# the table.
_rows = [
    ("Onset: first detectable\\tablenotemark{a}", _od["first_detectable"]),
    ("Onset: persistently detectable", _od["persistent_detectable"]),
    ("Onset: generator grid (7.2\\,d)", _od["coarse_7p2d_generator_grid"]),
    ("Grid: every 1\\,d", _g["1.0"]),
    ("Grid: every 2\\,d", _g["2.0"]),
    ("Rule: 2 consecutive crossings", _sen["persistence_consecutive_crossings"]["2"]),
    ("Rule: 3 consecutive crossings", _sen["persistence_consecutive_crossings"]["3"]),
    ("Rule: \\texttt{NonPSPL} is argmax", _sen["argmax_rule"]),
    ("Bands: all three revealed", _sen["bands"]["all_three_bands"]),
]
# A flat table with self-describing row labels. \cutinhead subheadings are the idiomatic AASTeX
# construct but cannot open a \startdata block, and \multicolumn raises "Misplaced \omit" inside
# deluxetable; neither is worth a fragile workaround for four labels.
os.makedirs(os.path.join(HERE, "outputs"), exist_ok=True)
_out = []
for _i, (_label, _v) in enumerate(_rows):
    _ci = _v["premature_ci_of_eligible"]
    _md = _v["median_lag_non_premature_days"]
    _row = r"%s & %.1f & $[%.1f,\,%.1f]$ & %.1f & %s" % (
        _label, 100 * _v["premature_rate_of_eligible"], 100 * _ci[0], 100 * _ci[1],
        100 * _v["detection_fraction"],
        ("$%+.1f$" % _md) if _md is not None else r"\nodata")
    _out.append(_row if _i == len(_rows) - 1 else _row + r" \\")
if not LIST_INPUTS:
    with open(os.path.join(HERE, "outputs", "cascade_policy_table.tex"), "w") as _f:
        _f.write("% AUTO-GENERATED by make_macros.py from validation/cascade_reproduce_result.json\n")
        _f.write("\n".join(_out) + "\n")

# PREVALENCE: thresholds chosen on the reserved validation rows, reported on final test. An
# earlier revision selected them on the final-test PR curve and reported on the same rows.
_prev_path = os.path.join(os.path.dirname(HERE), "validation", "prevalence_result.json")
if not os.path.exists(_prev_path):
    raise SystemExit(f"FATAL: {_prev_path} missing; run validation/prevalence_thresholds.py")
prv = _jload(_prev_path)
for _k, _nm in (("synthetic", "Synth"), ("one_pct", "One"), ("tenth_pct", "Tenth")):
    _s = prv["scenarios"][_k]
    cmd(f"bmlPrevComp{_nm}", three(_s["completeness_test"]))
    cmd(f"bmlPrevPur{_nm}", three(_s["purity_test"]))
    cmd(f"bmlPrevThr{_nm}", three(_s["threshold"]))
cmd("bmlPrevPurTarget", two(prv["purity_target"]))

s = cn["stress"]
cmd("bmlStressN", f"{s['n_events_millions']:.1f}")
cmd("bmlStressNatN", f"{s['natural_events_millions']:.1f}")
cmd("bmlStressMacroF", three(s["natural_macro_f1"]))
cmd("bmlSeedTrain", str(s["seed_base_train"]))
cmd("bmlSeedStress", str(s["seed_base_stress"]))

sr = cn["stress_regimes"]
cmd("bmlStressNatNp", three(sr["natural_np_recall"]))
cmd("bmlStressPlanetNp", three(sr["planetary_np_recall"]))
cmd("bmlStressPlanetPrec", three(sr["planetary_np_prec"]))
cmd("bmlStressWidesep", three(sr["widesep_np_recall"]))
cmd("bmlStressLongp", three(sr["longp_per_recall"]))
cmd("bmlStressShortte", three(sr["shortte_pspl_recall"]))
cmd("bmlStressFaintPspl", three(sr["faint_pspl_recall"]))
cmd("bmlStressFaintPrec", three(sr["faint_np_prec"]))
# The suite above was scored with the STAGE-5 checkpoint (aws/ud_bineval.sh), the released model's predecessor.
# validation/stress_rescore_local.py regenerates the first shards of each quoted tier with the suite's seeds and
# scores the same events with stage 5 and with the released checkpoint (third verification, 2026-09-13).
_srl_path = os.path.join(os.path.dirname(HERE), "validation", "stress_rescore_local.json")
if not os.path.exists(_srl_path):
    raise SystemExit(f"FATAL: {_srl_path} missing; run validation/stress_rescore_local.py")
_srl = _jload(_srl_path)
_q = _srl["quoted"]
_sub = _srl["subset"]
def _rel(k):
    return _q[k]["subset_released"]
cmd("bmlStressRelMacroF", three(_q["natural_macro_f1"]["subset_released"]))
cmd("bmlStressFiveSubMacroF", three(_q["natural_macro_f1"]["subset_stage5"]))
cmd("bmlStressSubNat", f"{_sub['natural']['released']['n']:,}")
cmd("bmlStressSubN", f"{sum(_sub[t]['released']['n'] for t in _sub if t != 'oor_pspl_shortte_current'):,}")
for _k, _nm in (("natural_np_recall", "NatNp"), ("natural_np_prec", "NatNpPrec"), ("planetary_np_recall", "PlanetNp"),
                ("planetary_np_prec", "PlanetPrec"), ("widesep_np_recall", "Widesep"), ("longp_per_recall", "Longp"),
                ("shortte_pspl_recall", "Shortte"), ("faint_pspl_recall", "FaintPspl"), ("faint_np_prec", "FaintPrec")):
    cmd(f"bmlStressRel{_nm}", three(_q[_k]["subset_released"]))
    cmd(f"bmlStressFiveSub{_nm}", three(_q[_k]["subset_stage5"]))
    cmd(f"bmlStressSuite{_nm}", three(_q[_k]["suite_stage5"]))
    cmd(f"bmlStressRel{_nm}N", f"{_q[_k]['n_subset']:,}")
# how close the regenerated subset is to the suite: stage 5 on the subset vs stage 5 on the suite. The subset is a new
# realisation (the suite's fleet ran an unpinned environment), so checkpoint comparisons are made within the subset.
_dev = {k: abs(_q[k]["subset_stage5"] - _q[k]["suite_stage5"]) for k in _q if k != "natural_macro_f1"}   # 'its OTHER numbers'
cmd("bmlStressSubDiffMax", three(max(_dev.values())))
cmd("bmlStressSubDiffMed", three(float(np.median(list(_dev.values())))))
_fr_sub, _fr_suite = _sub["natural"]["released"]["label_fractions"]["NonPSPL"], _srl["suite_label_fractions"]["natural"]["NonPSPL"]
cmd("bmlStressNatAnomDeficit", f"{100 * (1 - _fr_sub / _fr_suite):.1f}")
_fw_sub, _fw_suite = (_sub["oor_np_widesep"]["released"]["label_fractions"]["NonPSPL"],
                      _srl["suite_label_fractions"]["oor_np_widesep"]["NonPSPL"])
cmd("bmlStressWidesepAnomDeficit", f"{100 * (1 - _fw_sub / _fw_suite):.0f}")
# the sub-day sweep at the timescales of the RMDC26 comparison (0.25-1 d), corrected generator
_mt = _sub["oor_pspl_shortte_current"]["released"]["single_lens_above_frozen_tE_0p25_1"]
cmd("bmlStressShortteCurMatchedAlert", f"{100 * _mt['frac']:.0f}"); cmd("bmlStressShortteCurMatchedN", f"{_mt['n']:,}")
# faint photometry against the faint sweep's class mix (fifth verification: the mix does not explain the precision)
_pc = _srl["precision_counterfactual"]["released"]
cmd("bmlStressFaintPrecNatMix", three(_pc["faint_at_natural_mix"])); cmd("bmlStressNatPrecFaintMix", three(_pc["natural_at_faint_mix"]))
# PSPL recall by generator class: the suite's per-label PSPL recalls mix swept single lenses with demoted binaries
for _t, _nm in (("oor_pspl_shortte", "Shortte"), ("oor_pspl_shortte_current", "ShortteCur"), ("oor_flat_faint", "Faint")):
    _g = {c: _sub[_t][c]["pspl_label_by_generator_class"] for c in ("released", "stage5")}
    for _c, _cn in (("released", "Rel"), ("stage5", "FiveSub")):
        _sl = _g[_c]["single_lenses"]
        cmd(f"bmlStress{_cn}{_nm}Single", three(_sl["recall"]))
        cmd(f"bmlStress{_cn}{_nm}SingleNp", f"{100 * _sl['argmax_fractions']['NonPSPL']:.0f}")
        cmd(f"bmlStress{_cn}{_nm}SingleAlert", f"{100 * _sl['frac_above_frozen_threshold']:.0f}")
    cmd(f"bmlStressRel{_nm}SingleN", f"{_g['released']['single_lenses']['n']:,}")
    cmd(f"bmlStressRel{_nm}Demoted", three(_g["released"]["demoted_binaries"]["recall"]))
    cmd(f"bmlStress{_nm}DemotedShare", f"{100 * _g['released']['demoted_binaries']['weighted_share_of_label']:.0f}")
# anomaly calls: weighted prevalence and false-positive rate, and precision at the natural prevalence (prior shift)
_pn = _srl["precision_at_natural_prevalence"]
for _t, _nm in (("natural", "Nat"), ("planetary", "Planet"), ("oor_flat_faint", "Faint"), ("oor_np_widesep", "Widesep")):
    _r = _sub[_t]["released"]
    cmd(f"bmlStress{_nm}PrevW", f"{100 * _r['nonpspl_rates']['prevalence_w']:.2g}")
    cmd(f"bmlStressRel{_nm}Fpr", f"{100 * _r['nonpspl_rates']['fpr_w']:.1f}")
    cmd(f"bmlStressRel{_nm}MlFa", f"{100 * _r['pspl_label_false_anomaly_w']:.2g}")        # microlensing without an anomaly
    cmd(f"bmlStressRel{_nm}MlAlert", f"{100 * _r['pspl_label_above_frozen_w']:.2g}")
    cmd(f"bmlStress{_nm}BinDet", f"{100 * _r['binary_detectable_fraction_w']:.1f}")
    if _t in _pn and _t != "oor_flat_faint":    # the faint sweep's prior shift keeps its mix-diluted FPR; not quoted
        cmd(f"bmlStressRel{_nm}PrecNat", three(_pn[_t]["released"]))
cmd("bmlStressRelNatPsplN", f"{_sub['natural']['released']['per_class']['PSPL']['n']:,}")
cmd("bmlStressFaintBinShare", f"{100 * _sub['oor_flat_faint']['released']['true_class_fractions_w']['NonPSPL']:.0f}")
cmd("bmlStressNatBinShare", f"{100 * _sub['natural']['released']['true_class_fractions_w']['NonPSPL']:.0f}")
# The directional sentences of Sec. limits and the abstract about these numbers (third and fourth verifications).
def _need(ok, what):
    if not ok:
        raise SystemExit(f"FATAL: stress sentence no longer holds: {what}")
_need(abs(_q["natural_macro_f1"]["subset_released"] - h["macro_f1"]) <= 0.005,
      "the released model 'reproduces' its held-out macro-F1 on the natural subset")
_need(abs(_q["natural_macro_f1"]["subset_stage5"] - _q["natural_macro_f1"]["suite_stage5"]) <= 0.005,
      "stage 5 on the subset gives the full set's macro-F1")
_need(set(sorted(_dev, key=_dev.get)[-2:]) == {"widesep_np_recall", "faint_pspl_recall"},
      "the two largest subset-vs-full-set differences are the wide-separation and faint-source recalls")
_need(_fw_sub < 0.85 * _fw_suite, "the regenerated wide-separation sweep labels clearly fewer detectable anomalies than the set")
# every other tier's label fractions agree with the set within binomial noise (the two deficits above are disclosed)
for _t in ("planetary", "oor_per_longp", "oor_pspl_shortte", "oor_flat_faint"):
    _n = _sub[_t]["released"]["n"]
    for _c, _fs in _srl["suite_label_fractions"][_t].items():
        _f = _sub[_t]["released"]["label_fractions"][_c]
        _se = max(np.sqrt(_fs * (1 - _fs) / _n), 1e-9)
        # sixth check: the bound sits below the disclosed deficits (|z| 2.9 natural, 2.5 wide-separation), so a tier that
        # deviated as much as those would not be called in agreement
        _need(abs(_f - _fs) / _se < 2.5, f"the regenerated {_t} tier's {_c} fraction differs from the set's ({_f:.4f} vs {_fs:.4f})")
_need(_pc["faint_at_natural_mix"] < 0.5 * _pc["natural"] and _pc["natural_at_faint_mix"] > 0.8 * _pc["natural"],
      "faint photometry, not the sweep's class mix, drives most of the fall in faint-sweep precision")
_need(_mt["frac"] > 3 * _sub["natural"]["released"]["pspl_label_above_frozen_w"], "the matched-timescale sub-day rate is far above the natural one")
# the abstract's range "legacy--corrected" is printed low to high (sixth check)
_need(_sub["oor_pspl_shortte"]["released"]["pspl_label_by_generator_class"]["single_lenses"]["frac_above_frozen_threshold"]
      <= _sub["oor_pspl_shortte_current"]["released"]["pspl_label_by_generator_class"]["single_lenses"]["frac_above_frozen_threshold"],
      "the abstract's sub-day range runs from the legacy tier (low) to the corrected tier (high)")
_need(_q["natural_np_recall"]["subset_stage5"] - _q["natural_np_recall"]["suite_stage5"] > 0.005 and _fr_sub < _fr_suite,
      "the regenerated natural tier has fewer detectable anomalies and stage 5's recall on it differs from the full set's")
_need(_rel("widesep_np_recall") < 0.5, "wide-separation anomaly recall 'falls'")
_need(_rel("longp_per_recall") < 0.1, "long-period PeriodicVar recall is 'a nearly complete failure'")
for _t in ("oor_pspl_shortte", "oor_pspl_shortte_current"):
    _sd = _sub[_t]["released"]["pspl_label_by_generator_class"]
    _need(_sd["single_lenses"]["recall"] < 0.5 and _sd["single_lenses"]["argmax_fractions"]["NonPSPL"] > 0.5,
          f"{_t}: 'only' a minority of sub-day single lenses is classified PSPL and 'most' are called anomalies")
    _need(_sd["demoted_binaries"]["recall"] > 0.8 and _sd["demoted_binaries"]["weighted_share_of_label"] > 0.2,
          f"{_t}: the per-label sub-day recall is propped up by demoted binaries that the model recovers")
_rn, _rf = _sub["natural"]["released"], _sub["oor_flat_faint"]["released"]
_need(_rf["pspl_label_false_anomaly_w"] > 3 * _rn["pspl_label_false_anomaly_w"] and _rf["pspl_label_above_frozen_w"] > 5 * _rn["pspl_label_above_frozen_w"],
      "the false-anomaly rate among faint microlensing events 'rises' well above the natural population's")
for _t in ("oor_pspl_shortte", "oor_pspl_shortte_current"):
    _need(_sub[_t]["released"]["pspl_label_by_generator_class"]["single_lenses"]["frac_above_frozen_threshold"] > 5 * _rn["pspl_label_above_frozen_w"],
          f"{_t}: sub-day single lenses cross the threshold far more often than natural microlensing events")
_need(_srl["subset"]["oor_flat_faint"]["released"]["nonpspl_rates"]["prevalence_w"] < 0.1 * _srl["subset"]["natural"]["released"]["nonpspl_rates"]["prevalence_w"],
      "the faint tier's anomaly prevalence is far below the natural one")
_need(_pn["planetary"]["released"] >= _rel("natural_np_prec"), "low-q precision falls 'only through prevalence'")
_need(_rel("planetary_np_recall") >= _rel("natural_np_recall") - 0.1, "low-q anomaly recall 'holds'")
# Support behind each quoted OOR number = the swept class's per-class n in that regime, read from
# the stress report itself. The regime TOTALS (~82k) are mostly in-distribution filler: the OOR
# shard mix had a duplicate-key bug (run_shard.py) that left the swept class at 500-1,000 per
# shard instead of 9,000, so the recalls rest on far fewer events than the totals suggest. The
# per-label PSPL recalls also mix swept single lenses with demoted binaries (run_shard.py comment);
# the paper quotes the single-lens split from stress_rescore_local.json.
_srep = _jload(os.path.join(HERE, "results", "stress_report.json"))
_regs = _srep.get("regimes") or _srep
def _swept_n(regime, cls):
    return int(_regs[regime]["per_class"][cls]["n"])
cmd("bmlStressNatNpN", f"{_swept_n('natural', 'NonPSPL'):,}")
cmd("bmlStressPlanetNpN", f"{_swept_n('planetary', 'NonPSPL'):,}")
cmd("bmlStressWidesepN", f"{_swept_n('oor_np_widesep', 'NonPSPL'):,}")
cmd("bmlStressLongpN", f"{_swept_n('oor_per_longp', 'PeriodicVar'):,}")
cmd("bmlStressShortteN", f"{_swept_n('oor_pspl_shortte', 'PSPL'):,}")
cmd("bmlStressFaintPsplN", f"{_swept_n('oor_flat_faint', 'PSPL'):,}")
cmd("bmlStressFaintNpN", f"{_swept_n('oor_flat_faint', 'NonPSPL'):,}")
if round(float(_regs["oor_np_widesep"]["per_class"]["NonPSPL"]["recall"]), 3) != round(float(sr["widesep_np_recall"]), 3):
    raise SystemExit("FATAL: canonical widesep recall no longer matches stress_report.json "
                     f"({sr['widesep_np_recall']} vs {_regs['oor_np_widesep']['per_class']['NonPSPL']['recall']})")

# the matched-density test, read from its artifact (sixth check: it had been hand-copied into canonical_numbers.json,
# and its uniform arm's collapse had been read as a sparsity floor; a gap-free regular arm and the empty-bin fractions
# now separate empty bins from sparsity)
_gmr = _jload(os.path.join(os.path.dirname(HERE), "validation", "gap_matched_result.json"))
if not all(k in _gmr for k in ("code", "checkpoint_sha256")) or not all("regular" in a_ for a_ in _gmr["arms"]):
    raise SystemExit("FATAL: gap_matched_result.json predates the regular arm; rerun validation/gap_matched_density.py")
_ga = sorted(_gmr["arms"], key=lambda a_: -a_["visits"])
if len(_ga) != 3:
    raise SystemExit("FATAL: the matched-density text describes three visit counts")
cmd("bmlGapN", str(_gmr["n_events"]))
for _a, _nm in zip(_ga, "ABC"):
    cmd(f"bmlGapVisits{_nm}", f"{_a['visits_per_day']:.0f}")
    cmd(f"bmlGapUniform{_nm}", three(_a["uniform"])); cmd(f"bmlGapNightly{_nm}", three(_a["nightly"]))
    cmd(f"bmlGapRegular{_nm}", three(_a["regular"]))
    cmd(f"bmlGapEmptyUniform{_nm}", f"{100 * _a['empty_bin_frac']['uniform']:.0f}")
cmd("bmlGapUniformALo", three(_ga[0]["uniform_ci"][0])); cmd("bmlGapUniformAHi", three(_ga[0]["uniform_ci"][1]))
cmd("bmlGapNightlyAHi", three(_ga[0]["nightly_ci"][1]))
cmd("bmlGapEmptyNightly", f"{100 * min(a_['empty_bin_frac']['nightly'] for a_ in _ga):.0f}")
if "full_cadence" not in _gmr:
    raise SystemExit("FATAL: gap_matched_result.json lacks the full-cadence arm; rerun validation/gap_matched_density.py")
cmd("bmlGapFull", three(_gmr["full_cadence"]["recall"]))
if not _gmr["full_cadence"]["ci"][0] > max(a_["regular_ci"][1] for a_ in _ga):
    raise SystemExit("FATAL: 'thinning alone costs recall too' no longer holds (full cadence vs the regular grids)")
_emp = [a_["empty_bin_frac"]["uniform"] for a_ in _ga]
if not (all(a_["nightly"] == 0 for a_ in _ga) and _ga[0]["uniform_ci"][0] > _ga[0]["nightly_ci"][1]
        and _ga[1]["uniform_ci"][0] > _ga[1]["nightly_ci"][1]):
    raise SystemExit("FATAL: 'the gapped schedule fails where uniform sampling works (intervals do not overlap)' no longer holds")
if not (_emp[0] < _emp[1] < _emp[2] and max(a_["empty_bin_frac"]["regular"] for a_ in _ga) == 0
        and _ga[2]["uniform_ci"][1] < _ga[2]["regular_ci"][0] and min(a_["regular"] for a_ in _ga) > 0.4
        and min(a_["empty_bin_frac"]["nightly"] for a_ in _ga) > 0.5):
    raise SystemExit("FATAL: 'empty two-hour bins, not sparsity, make the thinned schedules fail' no longer holds")

mr = cn["mass_ratio_regimes"]
for key, name in (("stellar", "Stellar"), ("giant", "Giant"),
                  ("neptune", "Neptune"), ("lowmass", "Lowmass")):
    cmd(f"bmlQ{name}Comp", three(mr[f"{key}_comp"]))
    cmd(f"bmlQ{name}N", f"{mr[f'{key}_n']:,}")

ft = cn["massregime_finetune"]
cmd("bmlFtEvalN", f"{ft['eval_n']:,}")
for key, name in (("stellar", "Stellar"), ("giant", "Giant"),
                  ("neptune", "Neptune"), ("lowmass", "Lowmass")):
    cmd(f"bmlFt{name}Before", three(ft[f"{key}_before"]))
    cmd(f"bmlFt{name}After", three(ft[f"{key}_after"]))
    cmd(f"bmlFt{name}N", str(ft[f"{key}_n"]))
# largest per-class F1 DROP after the fine-tune; 0 when no class regressed (was abs(min(...)),
# which would have reported the smallest improvement as a regression)
cmd("bmlFtWorstRegress", three(max(0.0, -min(ft[k] for k in ft if k.startswith("f1_") and k.endswith("_delta")))))

hr = cn["hardregime_finetune"]
for k, name in (("longp_periodic", "LongpPer"), ("widesep_nonpspl", "WidesepNp"),
                ("shortte_pspl", "Shortte"), ("faint_pspl", "FaintPspl")):
    cmd(f"bmlHr{name}Before", three(hr[f"{k}_before"]))
    cmd(f"bmlHr{name}After", three(hr[f"{k}_after"]))
cmd("bmlHrFaintLpvPrecBefore", three(hr["faint_lpv_prec_before"]))
cmd("bmlHrFaintLpvPrecAfter", three(hr["faint_lpv_prec_after"]))
cmd("bmlHrFaintLpvRecBefore", three(hr["faint_lpv_recall_before"]))
cmd("bmlHrFaintLpvRecAfter", three(hr["faint_lpv_recall_after"]))
cmd("bmlHrWidesepN", str(hr["widesep_n"]))
cmd("bmlHrNatNpPrecBefore", three(hr["natural_nonpspl_prec_before"]))
cmd("bmlHrNatNpPrecAfter", three(hr["natural_nonpspl_prec_after"]))

# ABLATIONS: read the artifacts directly, like the cascade block. Fourteen of these numbers used
# to be hand-copied into canonical_numbers.json, which is one transcription step away from the
# prose/artifact drift that produced the withdrawn 42%->9% claim.
#
# The cascade arm comes from the original four-arm run; the labelling arms come from the rerun that
# holds the loss weights fixed across arms (the first run confounded labels with weighting, because
# pipeline.train derives class weights from whichever labels it is handed).
def _load(fname, required):
    path = os.path.join(os.path.dirname(HERE), "validation", fname)
    if not os.path.exists(path):
        raise SystemExit(f"FATAL: {path} missing; run the experiment that produces it")
    obj = _jload(path)
    cur = obj
    for key in required:                      # required is a path into the nested schema
        if key not in cur:
            raise SystemExit(f"FATAL: {fname} lacks '{'/'.join(required)}'; regenerate it "
                             f"(schema changed -- do not hand-edit the JSON)")
        cur = cur[key]
    return obj

abl = _load("ablations_result.json", ("cascade_on", "realtime", "premature_rate_thr"))
cmd("bmlAbCascN", str(abl["cascade_on"]["realtime"]["n_eligible"]))
for tag, nm in (("cascade_on", "CascOn"), ("cascade_off", "CascOff")):
    rt, st = abl[tag]["realtime"], abl[tag]["static"]
    cmd(f"bmlAb{nm}PremThr", three(rt["premature_rate_thr"]))
    cmd(f"bmlAb{nm}PremArgmax", three(rt["premature_rate_argmax"]))
    cmd(f"bmlAb{nm}Det", three(rt["detection_fraction_thr"]))
    cmd(f"bmlAb{nm}MacroFOne", three(st["macro_f1"]))
# sixth check: the ablation's onsets are the generator's 7.2 d grid: t_anom is the first 7.2 d cut at which the anomaly is
# detectable, so it was undetectable at t_anom - 7.2 and an alert between the two may be on time. An alert at or before
# t_anom - 7.2 came before a point at which the anomaly was still undetectable. Detectability is not monotone, so the
# first-detectable onset can lie earlier still; the in-house trace (same generator) measures how often (seventh check).
_ab_unamb = {}
for tag, nm in (("cascade_on", "CascOn"), ("cascade_off", "CascOff")):
    _ev = abl[tag]["realtime"]["events"]
    _ta = np.array([e["t_anom"] for e in _ev], float)
    if not np.allclose(np.round(_ta / 7.2) * 7.2, _ta):
        raise SystemExit("FATAL: the ablation's onsets are no longer on the 7.2 d generator grid; the text says they are")
    for rule, rnm in (("thr", "Thr"), ("argmax", "Argmax")):
        _f = np.array([np.nan if e[f"first_{rule}"] is None else e[f"first_{rule}"] for e in _ev], float)
        _pm = np.array([bool(e[f"premature_{rule}"]) for e in _ev])
        if not np.array_equal(_pm, np.isfinite(_f) & (_f < _ta)):
            raise SystemExit("FATAL: the ablation's premature flags disagree with its alert and onset times")
        _un = int((_pm & (_f <= _ta - 7.2 + 1e-9)).sum())
        _ab_unamb[(tag, rule)] = (_un, int(_pm.sum()))
        cmd(f"bmlAb{nm}PremK{rnm}", str(int(_pm.sum()))); cmd(f"bmlAb{nm}Unamb{rnm}", str(_un))
        cmd(f"bmlAb{nm}InWin{rnm}", str(int(_pm.sum()) - _un))
if not all(_ab_unamb[("cascade_on", r)][0] < _ab_unamb[("cascade_off", r)][0] for r in ("thr", "argmax")):
    raise SystemExit("FATAL: 'alerts at or before the cut before the grid onset favour the augmented arm under both rules' no longer holds")
_tr = np.load(os.path.join(os.path.dirname(HERE), "validation", "cascade_trace.npz"))
INPUTS.append(os.path.join(os.path.dirname(HERE), "validation", "cascade_trace.npz"))
_tf, _tco = _tr["t_anom_fine"].astype(float), _tr["t_anom_coarse"].astype(float)
_ok = np.isfinite(_tf) & np.isfinite(_tco)
cmd("bmlAbFineBeforePrevCutPct", f"{100 * np.mean(_tf[_ok] < _tco[_ok] - 7.2 - 1e-9):.0f}")
if not 0 < np.mean(_tf[_ok] < _tco[_ok] - 7.2 - 1e-9) < 0.15:
    raise SystemExit("FATAL: 'the first-detectable onset precedes the previous grid cut for a minority of binaries' no longer holds")
if _ab_unamb[("cascade_on", "thr")][0] != 0:
    raise SystemExit("FATAL: 'all of the augmented arm's premature alerts at the threshold fall inside the grid window' no longer holds")
if not all(1 - _ab_unamb[("cascade_on", r)][0] / _ab_unamb[("cascade_on", r)][1] >= 0.9 for r in ("thr", "argmax")):
    raise SystemExit("FATAL: 'almost all of the augmented arm's premature alerts fall inside the grid window' no longer holds")
if not (abl["cascade_on"]["realtime"]["premature_rate_argmax"] > abl["cascade_off"]["realtime"]["premature_rate_argmax"]
        and abl["cascade_on"]["realtime"]["premature_rate_thr"] < abl["cascade_off"]["realtime"]["premature_rate_thr"]):
    raise SystemExit("FATAL: on the 7.2 d grid the two rules no longer move the premature rate in opposite directions")

lab2 = _load("labelling_ablation_result.json", ("arms", "labels_observational"))
for tag, nm in (("labels_observational", "LabelObs"), ("labels_generator", "LabelGen"),
                ("labels_generator_ownweights", "LabelGenOwnW")):
    a = lab2["arms"][tag]
    cmd(f"bmlAb{nm}MacroFOne", three(a["vs_observational"]["macro_f1"]))
    cmd(f"bmlAb{nm}MacroFOneGen", three(a["vs_generator"]["macro_f1"]))
    for cls, cnm in (("PSPL", "Pspl"), ("NonPSPL", "Nonpspl")):
        cmd(f"bmlAb{nm}{cnm}FOne", three(a["vs_observational"]["per_class_f1"][cls]))
    cmd(f"bmlAb{nm}Comp", three(a["anomaly_completeness_at_thr"]))
    cmd(f"bmlAb{nm}Pur", three(a["anomaly_purity_at_thr"]))
# "about N non-anomalous flags for every detectable anomaly it flags" follows from the purity alone
_pg = lab2["arms"]["labels_generator"]["anomaly_purity_at_thr"]
if not 0 < _pg < 0.2:
    raise SystemExit("FATAL: the generator-intent arm's purity no longer implies many false flags per true one")
cmd("bmlAbLabelGenFalsePerTrue", f"{(1 - _pg) / _pg:.0f}")
_gap = lab2["macro_f1_gap_vs_observational"]
cmd("bmlAbLabelGap", three(_gap["point"]))
cmd("bmlAbLabelGapLo", three(_gap["ci95"][0]))
cmd("bmlAbLabelGapHi", three(_gap["ci95"][1]))
cmd("bmlAbLabelNeval", f'{lab2["n_eval"]:,}')
cmd("bmlAbLabelEpochs", str(lab2["config"]["epochs"]))
# MATCHED-DETECTION cascade comparison: the experiment the previous revision named as the paper's
# clearest outstanding weakness. Read fail-closed like the others.
mtc = _load("cascade_matched_result.json", ("matched", "detection_0.60"))
cmd("bmlMatchN", f'{mtc["n_eligible"]:,}')
for _t, _nm in (("0.60", "Sixty"), ("0.80", "Eighty"), ("0.90", "Ninety")):
    _r = mtc["matched"][f"detection_{_t}"]
    cmd(f"bmlMatchOn{_nm}", pct(_r["cascade_on"]["premature_rate_of_eligible"]))
    cmd(f"bmlMatchOff{_nm}", pct(_r["cascade_off"]["premature_rate_of_eligible"]))
    cmd(f"bmlMatchP{_nm}", f'{_r["mcnemar"]["p_two_sided_conditional"]:.4g}')
    cmd(f"bmlMatchP{_nm}Adj", f'{_r["mcnemar"]["p_bonferroni_conditional"]:.4g}')
    cmd(f"bmlMatchOn{_nm}Hi", pct(_r["cascade_on"]["premature_ci_of_eligible"][1]))
    # McNemar discordant counts. The reducer's convention is a = cascade_on, b = cascade_off (its
    # delta is named on_minus_off), so n_a_only = premature in the augmented arm only, n_b_only =
    # premature in the unaugmented arm only. Previously the 0.60 counts were hand-typed in the prose.
    cmd(f"bmlMatchDiscord{_nm}", str(_r["mcnemar"]["n_discordant"]))
    cmd(f"bmlMatchOnOnly{_nm}", str(_r["mcnemar"]["n_a_only"]))
    cmd(f"bmlMatchOffOnly{_nm}", str(_r["mcnemar"]["n_b_only"]))



cx = cn["cadence_experiment"]
# The paper bounds the per-class F1 difference between cadence arms. Compute the bound rather than
# asserting it in prose: a bound that is typed by hand is a bound nobody rechecks.
_cadraw = os.path.join(os.path.dirname(HERE), "validation", "cadence_result.json")
if os.path.exists(_cadraw):
    _cd = _jload(_cadraw)
    _f1 = [_a["per_class_f1"] for _a in _cd]
    cmd("bmlCadMaxFOneDelta",
        f'{max(abs(_f1[0][k] - _f1[1][k]) for k in _f1[0]):.3f}')
cmd("bmlCadN", f"{cx['n_events']:,}")
# Per-arm surviving-event counts. canonical_numbers stores only the 15-min arm's value, and the
# paper previously presented it as "matched ... events", which it is not: the arms are matched by
# construction (same shards, seed, epochs) and their surviving counts differ by a few dozen events.
_cadraw2 = os.path.join(os.path.dirname(HERE), "validation", "cadence_result.json")
if os.path.exists(_cadraw2):
    _cd2 = {int(_a["cadence_min"]): _a for _a in _jload(_cadraw2)}
    cmd("bmlCadNfifteen", f"{_cd2[15]['n_events']:,}")
    cmd("bmlCadNtwelve", f"{_cd2[12]['n_events']:,}")
cmd("bmlCadEpochs", str(cx["epochs"]))
# Held-out evaluation (validation/cadence_local.py, 2026-09-09): both arms score the same number of
# disjoint-seed events, so one macro. The training-pool APs are kept to state the measured
# inflation of the earlier, training-inclusive protocol.
# The two held-out pools are the same seeds but not the same size (the detectability cuts keep
# different events at different cadences), exactly as the training pools differ; report both.
cmd("bmlCadEvalNfifteen", f"{cx['n_eval_events_15']:,}")
cmd("bmlCadEvalNtwelve", f"{cx['n_eval_events_12']:,}")
cmd("bmlCadFifteenApTrainpool", three(cx["trainpool_c15_ap"]))
cmd("bmlCadTwelveApTrainpool", three(cx["trainpool_c12_ap"]))
for k, name in (("completeness", "Completeness"), ("purity", "Purity"),
                ("ap", "Ap"), ("nonpspl_f1", "Nonpspl")):   # no digits: TeX names are letters only
    cmd(f"bmlCadFifteen{name}", three(cx[f"c15_{k}"]))
    cmd(f"bmlCadTwelve{name}", three(cx[f"c12_{k}"]))

bl = cn["baselines"]
cmd("bmlBaseBinml", three(bl["ap_binml"]))
cmd("bmlBaseGbt", three(bl["ap_gbt"]))
cmd("bmlBaseLogistic", three(bl["ap_logistic"]))
cmd("bmlBasePspl", three(bl["ap_fitted_pspl"]))
cmd("bmlBaseNtest", f"{bl['n_test']:,}")
# the comparison set's own anomaly prevalence (sixth check: its class mix was not described), cross-checked with the artifact
_blr = _jload(os.path.join(os.path.dirname(HERE), "validation", "baselines_result.json"))
if not (abs(_blr["nonpspl_prevalence"] - bl["prevalence"]) < 1e-9 and abs(_blr["ap_binml"] - bl["ap_binml"]) < 1e-9
        and abs(_blr["ap_fitted_pspl_residual"] - bl["ap_fitted_pspl"]) < 1e-9 and _blr["n_test"] == bl["n_test"]):
    raise SystemExit("FATAL: canonical baselines no longer match validation/baselines_result.json")
cmd("bmlBasePrev", f"{100 * _blr['nonpspl_prevalence']:.1f}")

# THROUGHPUT: read from the reproducible benchmark, never hand-entered. The 1,224 events/s of an earlier revision had
# no retained script or hardware record; the benchmark on an idle machine gives 1,015/s, about 17% below it, while its
# first committed run (359/s) was taken under load (sixth check). The text calls the machine otherwise idle, so the repeats
# must be tight and the load low.
_inf_path = os.path.join(os.path.dirname(HERE), "validation", "inference_benchmark_result.json")
if not os.path.exists(_inf_path):
    raise SystemExit(f"FATAL: {_inf_path} missing; run validation/inference_benchmark.py")
inf = _jload(_inf_path)
cmd("bmlInferEps", f"{inf['events_per_sec']:,}")
cmd("bmlInferMs", two(inf["ms_per_event"]))
cmd("bmlInferCores", str(inf["environment"]["logical_cores"]))
cmd("bmlInferCpu", inf["environment"]["cpu"])
cmd("bmlInferThreads", str(inf["environment"]["torch_threads"]))
_sb = inf["seconds_per_batch"]
if not ("load_average_1_5_15_min_before" in inf and _sb["max"] / _sb["min"] < 1.2
        and inf["load_average_1_5_15_min_before"][0] < inf["environment"]["logical_cores"] / 2):
    raise SystemExit("FATAL: the throughput run was not on an otherwise idle machine (spread or load too high)")

for _k, _nm in (("missed_anomaly_rate", "MissedRate"), ("lpv_to_pspl_rate", "LPVtoPSPL")):
    if _k not in fs:
        raise SystemExit(f"FATAL: figures_stats lacks '{_k}'; rerun make_figures.py")
    cmd("bml" + _nm, three(fs[_k]))

ia = cn["infra"]
cmd("bmlSimEvents", f"{ia['sim_events_millions']:.0f}")
cmd("bmlSimInstances", str(ia["sim_instances"]))
cmd("bmlSimVcpus", str(ia["sim5_vcpus_each"]))          # the v5 fleets (sim_* is the earlier v4 run)
cmd("bmlSimEps", str(ia["sim_events_per_sec"]))
cmd("bmlSimHours", str(ia["sim_hours"]))
cmd("bmlSimRegion", ia["sim5_region"])
cmd("bmlTrainDevice", ia["train_device"])
cmd("bmlTrainEps", f"{ia['train_events_per_sec']:,}")
cmd("bmlTrainBatch", str(ia["train_batch"]))
cmd("bmlTrainHours", str(ia["train_hours"])); cmd("bmlTrainHoursTypical", str(ia["train_hours_typical"]))
cmd("bmlTrainStages", str(ia["train_stages"]))
cmd("bmlTrainFinalEvents", f"{ia['train_final_stage_events'] / 1e6:.1f}")
cmd("bmlTrainBaseEvents", f"{ia['train_base_events']:,}")
cmd("bmlTrainBatchBench", str(ia["train_batch_benchmark"]))
cmd("bmlTrainEpsLo", str(ia["train_epoch_events_per_sec_lo"])); cmd("bmlTrainEpsHi", str(ia["train_epoch_events_per_sec_hi"]))
cmd("bmlTrainEpochs", str(ia["train_epochs_effective"]))

sl = cn["slices"]
# the slices are hand-copied into canonical_numbers.json; check them against the frozen metrics.json (the
# no-blue-band slice can only be read there: the per-event band counts were not saved; fifth verification)
_mj = _jload(os.path.join(HERE, "results", "metrics.json"))["slices"]
for _cname, _mname in (("deep_planetary_q_lt_1e-3", "deep_planetary_q_lt_1e-3"), ("planetary_q_lt_1e-2", "planetary_q_lt_1e-2"),
                       ("near_suzuki_break", "near_suzuki_break"), ("faint_mbase_gt_22p5", "faint_mbase_gt_22.5"),
                       ("no_blue_band", "no_blue_band")):
    if abs(sl[_cname]["recall"] - _mj[_mname]["recall"]) > 5e-4:
        raise SystemExit(f"FATAL: canonical slice {_cname} ({sl[_cname]['recall']}) disagrees with metrics.json ({_mj[_mname]['recall']})")
if sl["no_blue_band"]["n"] != _mj["no_blue_band"]["n_true_nonpspl"]:
    raise SystemExit("FATAL: the no-blue-band slice count disagrees with metrics.json")
cmd("bmlSliceDeepPlanet", three(sl["deep_planetary_q_lt_1e-3"]["recall"]))
cmd("bmlSlicePlanet", three(sl["planetary_q_lt_1e-2"]["recall"]))
cmd("bmlSliceSuzuki", three(sl["near_suzuki_break"]["recall"]))
cmd("bmlSliceFaint", three(sl["faint_mbase_gt_22p5"]["recall"]))
cmd("bmlSliceNoBlue", three(sl["no_blue_band"]["recall"]))

m = cn["model"]
cmd("bmlNparams", f"{m['n_params']:,}")
cmd("bmlNtokens", str(m["n_tokens"]))
cmd("bmlDmodel", str(m["d_model"]))
cmd("bmlNlayers", str(m["n_layers"]))
cmd("bmlNheads", str(m["n_heads"]))
cmd("bmlBinsF", str(m["bins_f146"]))
cmd("bmlEpochsF", f"{m['epochs_f146']:,}")
cmd("bmlCadence", str(m["cadence_f146_min"]))
cmd("bmlWindow", str(m["window_days"]))

# derived-in-make_figures numbers
if "ap_oracle_dchi2" in fs:
    cmd("bmlAPoracle", three(fs["ap_oracle_dchi2"]))
if "ap_network" in fs:
    cmd("bmlAPnet", three(fs["ap_network"]))
if "prior_pi0" in fs:
    cmd("bmlPriorPiZero", pct(fs["prior_pi0"]))
    cmd("bmlPurityOnePct", three(fs["purity_pi_1pct"]))
    cmd("bmlPurityTenthPct", three(fs["purity_pi_p1pct"]))
for _k, _nm in (("conf_nonpspl_to_pspl_pct", "ConfNpToPspl"),
                ("conf_pspl_to_nonpspl_pct", "ConfPsplToNp"),
                ("gen_nonpspl_demoted_pct", "GenNpDemoted"),
                ("no_f087_pct", "NoFilterBlue")):
    # Previously bare literals in paper.tex. The F087-loss one disagreed with the artifact by a
    # factor of nearly two, which is exactly what hard-coded prose numbers do.
    if _k not in fs:
        raise SystemExit(f"FATAL: figures_stats lacks '{_k}'; rerun make_figures.py")
    cmd("bml" + _nm, f"{fs[_k]:.1f}")

if "eff_cond_recall_median" in fs:
    cmd("bmlEffMedian", three(fs["eff_cond_recall_median"]))
# where the in-distribution misses sit (fourth to sixth checks): wide binaries, at every evidence strength up to
# dchi2 = 1e6, and weak anomalies at smaller separations
for _k in ("miss_dchi2_gt_1e4_pct", "miss_dchi2_median", "miss_wide_pct", "np_to_pspl_wide_pct", "det_wide_pct", "recall_wide",
           "recall_not_wide", "comp_wide", "comp_not_wide", "recall_weakest_not_wide", "fp_demoted_binary_pct",
           "pspl_to_np_demoted_pct", "det_q_median", "det_stellar_pct", "s_top_bin", "eff_cond_recall_wide_stellar_lo",
           "eff_cond_recall_wide_stellar_hi", "eff_nd_wide_stellar_min", "eff_cond_recall_min", "eff_cond_recall_min_logq_hi"):
    if _k not in fs:
        raise SystemExit(f"FATAL: figures_stats lacks '{_k}'; rerun make_figures.py")
cmd("bmlMissHighEvPct", f"{fs['miss_dchi2_gt_1e4_pct']:.0f}"); cmd("bmlMissDchiMedian", f"{fs['miss_dchi2_median']:,.0f}")
cmd("bmlMissWidePct", f"{fs['miss_wide_pct']:.0f}"); cmd("bmlNpToPsplWidePct", f"{fs['np_to_pspl_wide_pct']:.0f}")
cmd("bmlDetWidePct", f"{fs['det_wide_pct']:.0f}"); cmd("bmlSTopBin", f"{fs['s_top_bin']:.1f}")
cmd("bmlRecallWide", three(fs["recall_wide"])); cmd("bmlRecallNotWide", three(fs["recall_not_wide"]))
cmd("bmlCompWide", three(fs["comp_wide"])); cmd("bmlCompNotWide", three(fs["comp_not_wide"]))
cmd("bmlRecallWeakestNotWide", three(fs["recall_weakest_not_wide"]))
cmd("bmlFpDemotedPct", f"{fs['fp_demoted_binary_pct']:.1f}"); cmd("bmlPsplToNpDemotedPct", f"{fs['pspl_to_np_demoted_pct']:.1f}")
cmd("bmlDetQmed", f"{fs['det_q_median']:.2f}"); cmd("bmlDetStellarPct", f"{fs['det_stellar_pct']:.0f}")
cmd("bmlEffWideStellarLo", f"{fs['eff_cond_recall_wide_stellar_lo']:.2f}"); cmd("bmlEffWideStellarHi", f"{fs['eff_cond_recall_wide_stellar_hi']:.2f}")
cmd("bmlEffMin", f"{fs['eff_cond_recall_min']:.2f}")
cmd("bmlEffMinLogqLo", f"{fs['eff_cond_recall_min_logq_lo']:g}"); cmd("bmlEffMinLogqHi", f"{fs['eff_cond_recall_min_logq_hi']:g}")
for _k in ("wide_miss_rate_by_dchi2_lo", "wide_miss_rate_by_dchi2_hi", "notwide_weak_share_of_det_pct", "notwide_weak_share_of_miss_pct",
           "notwide_miss_rate_weak", "notwide_miss_rate_strong", "recall_wide_bigq", "recall_wide_smallq", "wide_miss_bigq_pct",
           "thr_miss_pct_of_det", "thr_miss_wide_pct", "eff_cond_recall_wide_bigq_lo", "eff_cond_recall_wide_bigq_hi",
           "eff_nd_wide_bigq_min", "eff_nd_min_cell", "eff_nd_median_populated"):
    if _k not in fs:
        raise SystemExit(f"FATAL: figures_stats lacks '{_k}'; rerun make_figures.py")
cmd("bmlWideMissLo", f"{100 * fs['wide_miss_rate_by_dchi2_lo']:.0f}"); cmd("bmlWideMissHi", f"{100 * fs['wide_miss_rate_by_dchi2_hi']:.0f}")
cmd("bmlNotWideWeakDet", f"{fs['notwide_weak_share_of_det_pct']:.0f}"); cmd("bmlNotWideWeakMiss", f"{fs['notwide_weak_share_of_miss_pct']:.0f}")
cmd("bmlNotWideMissWeak", three(fs["notwide_miss_rate_weak"])); cmd("bmlNotWideMissStrong", three(fs["notwide_miss_rate_strong"]))
cmd("bmlRecallWideBigq", three(fs["recall_wide_bigq"])); cmd("bmlRecallWideSmallq", three(fs["recall_wide_smallq"]))
cmd("bmlWideMissBigqPct", f"{fs['wide_miss_bigq_pct']:.0f}")
cmd("bmlThrMissPct", f"{fs['thr_miss_pct_of_det']:.0f}"); cmd("bmlThrMissWidePct", f"{fs['thr_miss_wide_pct']:.0f}")
cmd("bmlEffWideBigqLo", f"{fs['eff_cond_recall_wide_bigq_lo']:.2f}"); cmd("bmlEffWideBigqHi", f"{fs['eff_cond_recall_wide_bigq_hi']:.2f}")
cmd("bmlEffWideBigqNd", f"{fs['eff_nd_wide_bigq_min']:,}"); cmd("bmlEffMinNd", str(fs["eff_nd_min_cell"]))
# sixth check: the strongest wide anomalies, where the misses go, the low-q corner, and the weighted mid-range calibration
for _k in ("wide_miss_rate_above_1e6", "wide_det_above_1e6_pct", "miss_to_pspl_pct", "eff_cond_recall_lowq_hi", "eff_nd_lowq_lo",
           "eff_nd_lowq_hi", "eff_n_lowq_cells", "calib_weight_below_0p1_pct", "calib_mid_mean_score", "calib_mid_anomaly_freq",
           "calib_mid_anomaly_freq_stored", "calib_top_mean_score", "calib_top_anomaly_freq", "calib_mid_mean_score_stored",
           "calib_ece_mid_share_pct"):
    if _k not in fs:
        raise SystemExit(f"FATAL: figures_stats lacks '{_k}'; rerun make_figures.py")
cmd("bmlWideMissTop", f"{100 * fs['wide_miss_rate_above_1e6']:.0f}"); cmd("bmlWideDetTopPct", f"{fs['wide_det_above_1e6_pct']:.0f}")
cmd("bmlMissToPsplPct", f"{fs['miss_to_pspl_pct']:.0f}")
cmd("bmlEffLowqHi", f"{fs['eff_cond_recall_lowq_hi']:.2f}"); cmd("bmlEffNLowqCells", str(fs["eff_n_lowq_cells"]))
cmd("bmlEffLowqNdLo", str(fs["eff_nd_lowq_lo"])); cmd("bmlEffLowqNdHi", str(fs["eff_nd_lowq_hi"]))
cmd("bmlCalibLowWeightPct", f"{fs['calib_weight_below_0p1_pct']:.0f}")
cmd("bmlCalibMidScore", f"{fs['calib_mid_mean_score']:.2f}"); cmd("bmlCalibMidFreq", f"{fs['calib_mid_anomaly_freq']:.3f}")
cmd("bmlCalibMidFreqStored", f"{fs['calib_mid_anomaly_freq_stored']:.2f}")
cmd("bmlCalibMidScoreStored", f"{fs['calib_mid_mean_score_stored']:.2f}"); cmd("bmlCalibEceMidPct", f"{fs['calib_ece_mid_share_pct']:.0f}")
cmd("bmlCalibTopScore", f"{fs['calib_top_mean_score']:.2f}"); cmd("bmlCalibTopFreq", f"{fs['calib_top_anomaly_freq']:.2f}")
# the directional sentences of Sec. results about where the misses sit (fourth and fifth verifications)
def _needfs(ok, what):
    if not ok:
        raise SystemExit(f"FATAL: Sec. results sentence no longer holds: {what}")
_needfs(fs["np_to_pspl_wide_pct"] > 50 and fs["miss_wide_pct"] > 50 and fs["det_wide_pct"] < 20,
        "'most' NonPSPL->PSPL confusions and 'more than half' of argmax misses are wide binaries, a small share of anomalies")
_needfs(0.15 <= fs["wide_miss_rate_by_dchi2_lo"] and fs["wide_miss_rate_by_dchi2_hi"] <= 0.35
        and fs["wide_miss_rate_by_dchi2_hi"] - fs["wide_miss_rate_by_dchi2_lo"] < 0.1,
        "wide binaries are missed at a similar rate 'at every evidence strength up to dchi2 = 1e6'")
_needfs(fs["wide_miss_rate_above_1e6"] < fs["wide_miss_rate_by_dchi2_lo"] - 0.05,
        "the strongest wide anomalies (dchi2 > 1e6) are missed less often")
_needfs(fs["miss_to_pspl_pct"] > 90, "a missed detectable binary is 'almost always called a single lens'")
_needfs(fs["eff_cond_recall_lowq_hi"] < fs["eff_cond_recall_median"] and fs["eff_nd_lowq_hi"] < fs["eff_nd_median_populated"] / 2,
        "every populated cell at log q < -4 lies below the plane's median, in thin support")
_needfs(fs["calib_weight_below_0p1_pct"] > 70 and fs["calib_ece_mid_share_pct"] > 50
        and fs["calib_mid_anomaly_freq"] < fs["calib_mid_mean_score"] / 2
        and fs["calib_mid_anomaly_freq_stored"] < fs["calib_mid_mean_score_stored"]
        and fs["calib_mid_mean_score"] - fs["calib_mid_anomaly_freq"] > fs["calib_mid_mean_score_stored"] - fs["calib_mid_anomaly_freq_stored"]
        and abs(fs["calib_top_mean_score"] - fs["calib_top_anomaly_freq"]) < 0.1,
        "the ECE is small because most weight sits below 0.1 but most of it comes from the over-confident mid-range, "
        "more so under weighting; above 0.9 score and frequency are close")
_needfs(fs["notwide_weak_share_of_miss_pct"] > 2 * fs["notwide_weak_share_of_det_pct"]
        and fs["notwide_miss_rate_weak"] > 10 * fs["notwide_miss_rate_strong"],
        "at smaller separations the misses 'concentrate at weak anomalies'")
_needfs(fs["recall_wide_bigq"] < fs["recall_wide_smallq"] - 0.15 and fs["wide_miss_bigq_pct"] > 80,
        "the wide-separation weakness is 'confined to q > 0.1'")
_needfs(fs["eff_cond_recall_wide_bigq_hi"] < fs["eff_cond_recall_median"] - 0.15 and fs["eff_nd_wide_bigq_min"] > 2 * fs["eff_nd_median_populated"],
        "the plane's wide q > 0.1 cells are 'well populated' and clearly below its median")
_needfs(fs["eff_nd_min_cell"] < fs["eff_nd_median_populated"] / 4, "the plane's minimum sits in a 'low-support' cell")
_needfs(fs["thr_miss_wide_pct"] < fs["miss_wide_pct"], "at the operating threshold a smaller share of the misses is wide")
_needfs(fs["det_stellar_pct"] > 50 and fs["det_q_median"] > 1e-2, "our detectable anomalies are mostly stellar-mass-ratio binaries")
_needfs(fs["nonpspl_kept_pct_w"] < fs["nonpspl_kept_pct"], "the stored-event fraction overstates the generated binaries' detectable fraction")
if "nonpspl_ece_weighted" in fs:
    cmd("bmlECE", f"{fs['nonpspl_ece_weighted']:.3f}")
    cmd("bmlBrier", f"{fs['nonpspl_brier_weighted']:.3f}")

if LIST_INPUTS:
    print("\n".join(os.path.relpath(p_, os.path.dirname(HERE)) for p_ in INPUTS))
    sys.exit(0)
header = "% AUTO-GENERATED by make_macros.py -- do not edit. Source: canonical_numbers.json\n"
with open(os.path.join(HERE, "paper_macros.tex"), "w") as f:
    f.write(header + "\n".join(L) + "\n")
print(f"wrote paper_macros.tex ({len(L)} macros)")
