#!/usr/bin/env python3
"""canonical_numbers.json (+ outputs/figures_stats.json) -> paper_macros.tex.

Every number in paper.tex is a \\bml* macro defined here, so the manuscript can never drift
from the evaluation artifact. Run after make_figures.py:  python make_macros.py
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))

cn = json.load(open(os.path.join(HERE, "canonical_numbers.json")))
fs_path = os.path.join(HERE, "outputs", "figures_stats.json")
fs = json.load(open(fs_path)) if os.path.exists(fs_path) else {}

L = []
def cmd(name, value):
    L.append(r"\newcommand{\%s}{%s}" % (name, value))

def pct(x):   return f"{100*x:.1f}"
def two(x):   return f"{x:.2f}"
def three(x): return f"{x:.3f}"

h = cn["headline"]
cmd("bmlNtest", f"{cn['test']['n_events']:,}")
cmd("bmlCompleteness", three(h["completeness_at_purity"]))
cmd("bmlCompletenessPct", pct(h["completeness_at_purity"]))
cmd("bmlCompletenessLo", three(h["completeness_ci_lo"]))
cmd("bmlCompletenessHi", three(h["completeness_ci_hi"]))
cmd("bmlPurity", three(h["purity_achieved"]))
cmd("bmlPurityTarget", two(h["purity_target"]))
cmd("bmlAP", three(h["average_precision"]))
cmd("bmlMacroF", three(h["macro_f1"]))

for c, v in cn["per_class"].items():
    if c == "note":
        continue
    cmd(f"bml{c}R", three(v["recall"]))
    cmd(f"bml{c}P", three(v["precision"]))
    cmd(f"bml{c}F", three(v["f1"]))

cmd("bmlNonpsplPhysP", three(cn["nonpspl_physical_precision"]))
cmd("bmlNonpsplDemoted", pct(cn["nonpspl_demoted_fraction"]))
cmd("bmlSliceStrongAnom", three(cn["nonpspl_recall_strong_anomaly"]))

sup = cn["per_class_support"]
for c in ["Flat", "PSPL", "NonPSPL", "PeriodicVar", "LongPeriodVar", "Eruptive"]:
    cmd(f"bmlSup{c}", f"{sup[c]:,}")

lab = cn["labelling"]
cmd("bmlRelabelled", f"{lab['overall_relabelled_pct']:.1f}")
cmd("bmlNonpsplKept", f"{lab['nonpspl_kept_pct']:.1f}")
cmd("bmlNonpsplToPspl", f"{lab['nonpspl_to_pspl_pct']:.1f}")
cmd("bmlLpvToFlat", f"{lab['lpv_to_flat_pct']:.1f}")

cas = cn["cascade"]
cmd("bmlPrematureBefore", pct(cas["premature_flag_before"]))
cmd("bmlPrematureAfter", pct(cas["premature_flag_after"]))
cmd("bmlPreonsetBefore", three(cas["preonset_p_before"]))
cmd("bmlPreonsetAfter", three(cas["preonset_p_after"]))
cmd("bmlMissedBefore", three(cas["missed_planet_before"]))
cmd("bmlMissedAfter", three(cas["missed_planet_after"]))

s = cn["stress"]
cmd("bmlStressN", f"{s['n_events_millions']:.1f}")
cmd("bmlStressNatN", f"{s['natural_events_millions']:.1f}")
cmd("bmlStressMacroF", three(s["natural_macro_f1"]))
cmd("bmlSeedTrain", str(s["seed_base_train"]))
cmd("bmlSeedStress", str(s["seed_base_stress"]))

inf = cn["inference"]
cmd("bmlInferEps", f"{inf['events_per_sec']:,}")
cmd("bmlInferMs", two(inf["ms_per_event"]))
cmd("bmlInferCores", str(inf["cpu_cores"]))
cmd("bmlDetLag", str(inf["median_detection_lag_days"]))

fp = cn["false_positive"]
cmd("bmlMissedRate", three(fp["missed_planet_rate"]))
cmd("bmlLPVtoPSPL", three(fp["long_period_var_to_pspl"]))

ia = cn["infra"]
cmd("bmlSimEvents", f"{ia['sim_events_millions']:.0f}")
cmd("bmlSimInstances", str(ia["sim_instances"]))
cmd("bmlSimVcpus", str(ia["sim_vcpus_each"]))
cmd("bmlSimEps", str(ia["sim_events_per_sec"]))
cmd("bmlSimHours", str(ia["sim_hours"]))
cmd("bmlSimRegion", ia["sim_region"])
cmd("bmlTrainDevice", ia["train_device"])
cmd("bmlTrainEps", f"{ia['train_events_per_sec']:,}")
cmd("bmlTrainBatch", str(ia["train_batch"]))
cmd("bmlTrainHours", str(ia["train_hours"]))

sl = cn["slices"]
cmd("bmlSliceDeepPlanet", three(sl["deep_planetary_q_lt_1e-3"]["recall"]))
cmd("bmlSlicePlanet", three(sl["planetary_q_lt_1e-2"]["recall"]))
cmd("bmlSliceSuzuki", three(sl["near_suzuki_break"]["recall"]))
cmd("bmlSliceFaint", three(sl["faint_mbase_gt_22p5"]["recall"]))
cmd("bmlSliceNoBlue", three(sl["no_blue_band"]["recall"]))

m = cn["model"]
cmd("bmlNparams", f"{m['n_params']:,}")
cmd("bmlNtokens", str(m["n_tokens"]))
cmd("bmlDmodel", str(m["d_model"]))
cmd("bmlNlayers", str(m["n_layers"]))
cmd("bmlNheads", str(m["n_heads"]))
cmd("bmlBinsF", str(m["bins_f146"]))
cmd("bmlEpochsF", f"{m['epochs_f146']:,}")
cmd("bmlCadence", str(m["cadence_f146_min"]))
cmd("bmlWindow", str(m["window_days"]))

# derived-in-make_figures numbers
if "ap_oracle_dchi2" in fs:
    cmd("bmlAPoracle", three(fs["ap_oracle_dchi2"]))
if "ap_network" in fs:
    cmd("bmlAPnet", three(fs["ap_network"]))

header = "% AUTO-GENERATED by make_macros.py -- do not edit. Source: canonical_numbers.json\n"
with open(os.path.join(HERE, "paper_macros.tex"), "w") as f:
    f.write(header + "\n".join(L) + "\n")
print(f"wrote paper_macros.tex ({len(L)} macros)")
